514-labs/moosestack

.github/workflows/release-igloo-cli.yaml, apps/create-igloo-app/package.json, apps/create-igloo-app/scripts/release.sh, apps/create-igloo-app/src/index.ts, apps/create-igloo-app/tsconfig.json, apps/igloo-kit-cli/package.json, pnpm-lock.yaml
Add the create igloo app package with the cli as a dependency using the init cli command
=> feat: add the create igloo app package

apps/igloo-kit-cli/Cargo.lock, apps/igloo-kit-cli/Cargo.toml, apps/igloo-kit-cli/src/cli/config.rs, apps/igloo-kit-cli/src/cli/mod.rs
* Adds a config file in `~/.igloo-config.toml`
* Add a feature flag for coming soon page and redirect to the discord server
=> feat: add config file for the CLI and defaults to onboarding people on the discord

CONTRIBUTING, rfd/0001/README.mdx
=> rfd(0001): Add RFD for Request for Discussion (RFD) Process

rfd/0001/README.mdx, scripts/rfd/new.js, scripts/rfd/template.mdx
* Adds a creation script for new RFDs
* Adds a template for a new RFD
* Update the current status of the RFD and correct some details to match the implementation
=> rfd(0001): published - implementation of creation script

.github/workflows/rfd-bot.yaml, rfd/0001/README.mdx
* Adds a github action bot to claim RFD numbers
* Edits RFD 0001 to reflect the current level of automation
=> chore(rfd): add github action for rfd number claiming

scripts/rfd/template.mdx
Small typo that made the syntax coloring not work.
=> fix: Fixes the RFD template formating

rfd/0002/README.mdx
First RFD about the system as a whole.
This describes what aim to cover and how we are thinking about it.
=> Rfd/0002 - Ecosystem Skeleton Architecture

.husky/pre-commit, apps/igloo-kit-cli/Cargo.lock, apps/igloo-kit-cli/Cargo.toml, apps/igloo-kit-docs/package.json, apps/web/package.json, pnpm-lock.yaml
Update sentry 
Fixes a bug with the recommit hook and no rust changed files
=> chore: update sentry

.husky/pre-commit, package.json, pnpm-lock.yaml
Change the setup for automated code formatting so that only files that are changed get formatted and automatically added to the current commit
=> chore: migrate to lintstaged for better experience

apps/igloo-kit-cli/Cargo.lock, apps/igloo-kit-cli/Cargo.toml, apps/igloo-kit-cli/src/cli.rs, apps/igloo-kit-cli/src/cli/display.rs, apps/igloo-kit-cli/src/cli/settings.rs
* Refactors the config loading logic to use a config crate
* Adds the ability to set configurations through environment.
This is needed so that we can introduce proper logging and configure it through env variables (CI)
=> feat: add the ability to configure the CLI through environment variables

apps/igloo-kit-cli/Cargo.lock, apps/igloo-kit-cli/Cargo.toml, apps/igloo-kit-cli/src/cli.rs, apps/igloo-kit-cli/src/cli/logger.rs, apps/igloo-kit-cli/src/cli/settings.rs
Adds a logger for us to be able to track all the actions taken during a user's session and help debug if something goes wrong
=> feat: add internal logger to help us debug

.github/workflows/release-igloo-cli.yaml, .github/workflows/test-igloo-cli.yaml
=> fix: remove useless caches

apps/igloo-kit-cli/Cargo.lock, apps/igloo-kit-cli/Cargo.toml, apps/igloo-kit-cli/src/cli/routines.rs, apps/igloo-kit-cli/src/infrastructure/olap/clickhouse.rs
Removes request from the dependency given its very low usage
=> chore: remove unused dependency

apps/moose-cli-npm/scripts/release-bin.sh
Updates the release script to enable moose to be published
=> fix: make the bin release for moose compatible with igloo bin

apps/create-moose-app/package.json, apps/create-moose-app/scripts/release.sh, apps/moose-cli-npm/package.json, apps/moose-cli-npm/scripts/release-cli.sh
Change the names for moose to follow the same pattern as for igloo to be able to register the names
=> fix: change name to available name

apps/moose-cli-npm/scripts/release-bin.sh
Fixing a typo in the bash script
=> fix: publish script for moose

apps/igloo-kit-cli/src/cli.rs, apps/igloo-kit-cli/src/cli/commands.rs, pnpm-lock.yaml
simplified the commands module by removing the unused add command and it's secondary handler. We'll be able to add this back in more elegantly when we have the need for this feature
=> removed unused add handler and command

apps/igloo-kit-cli/src/cli.rs, apps/igloo-kit-cli/src/cli/commands.rs, apps/igloo-kit-cli/src/cli/logger.rs, pnpm-lock.yaml
adding the standard for logging practices to the logger module in the form of module documentation.
=> created the standard for logging

apps/igloo-kit-cli/src/cli/local_webserver.rs, apps/igloo-kit-cli/src/cli/routines.rs
=> stopping docker containers on shutdown

apps/moose-cli-npm/scripts/release-cli.sh
Attempt to fix some empty package builds
=> fix: add filter to the install

apps/igloo-kit-cli/src/cli/local_webserver.rs, apps/igloo-kit-cli/src/cli/logger.rs, apps/igloo-kit-cli/src/cli/routines.rs, apps/igloo-kit-cli/src/cli/watcher.rs, apps/igloo-kit-cli/src/infrastructure/console.rs, apps/moose-console/src/app/api/console/route.ts
* adds the post from the CLI to the console
* Updates the pattern for debug logs to be more clear
=> feat: working push to console

apps/create-igloo-app/scripts/release.sh, apps/create-moose-app/scripts/release.sh, apps/igloo-cli-npm/scripts/release-bin.sh, apps/igloo-cli-npm/scripts/release-cli.sh, apps/moose-cli-npm/scripts/release-bin.sh, apps/moose-cli-npm/scripts/release-cli.sh, deploy/docker-fullstack-image/Dockerfile, deploy/docker-fullstack-image/README.md, deploy/docker-fullstack-image/clickhouse-config.xml, deploy/docker-fullstack-image/run-clickhouse.sh, deploy/docker-fullstack-image/supervisord.conf
This is a docker image for all in one dependencies with both clickhouse and redpandas installed.
It will probably require some tweaks but it is in the state where both processes are running at the same time in the image
=> All in one base docker image

apps/framework-docs/src/pages/getting-started.mdx, apps/framework-docs/src/pages/getting-started/installation.mdx
Trying again to see if this one works... will close the old branch / PR.
=> Install typo fixes - take 2

apps/create-moose-app/src/index.ts, apps/igloo-kit-cli/Cargo.lock, apps/igloo-kit-cli/Cargo.toml, apps/igloo-kit-cli/src/cli.rs, apps/igloo-kit-cli/src/cli/routines/initialize.rs, apps/igloo-kit-cli/src/cli/routines/start.rs, apps/igloo-kit-cli/src/infrastructure/olap/clickhouse.rs, apps/igloo-kit-cli/src/project.rs, apps/igloo-kit-cli/src/utilities.rs, apps/igloo-kit-cli/src/utilities/constants.rs, apps/igloo-kit-cli/src/utilities/git.rs, apps/igloo-kit-cli/tests/cli_init.rs
=> init command generates a node project

apps/moose-console/src/components/query-interface.tsx, apps/moose-console/src/lib/snippets.ts
https://linear.app/514/issue/514-561/debounce-the-query-for-local-useractivity-trigger
https://linear.app/514/issue/514-560/python-snippet-had-an-error
https://linear.app/514/issue/514-558/ask-from-chris-crane
=> Fix python snippet, no auto query, scroll data table

apps/framework-cli/deploy/kubernetes/moose-deployment.yaml, apps/framework-cli/deploy/kubernetes/moose-lb-service.yaml, apps/framework-cli/deploy/kubernetes/redpanda-cluster.yaml, apps/framework-cli/deploy/kubernetes/set-env-secret.sh, apps/framework-cli/deploy/kubernetes/set-redpanda-password.sh
Collection of scripts used to configure moose `dogfooding` Kubernetes cluster.
=> Scripts used for k8s cluster

apps/framework-cli/deploy/kubernetes/moose-deployment.yaml, apps/framework-cli/deploy/kubernetes/set-dockerhub-credentials.sh
* added Kubernetes secret for Docker Hub private repo access
* indented keys in yaml file
=> updates to support pulling container from private repo

apps/framework-docs/next.config.js, apps/moose-console/next.config.js, apps/web/next.config.js, pnpm-lock.yaml
=> chore: remove warning from sentry in dev mode

apps/framework-cli/src/cli/watcher.rs, apps/framework-cli/src/framework/controller.rs, apps/framework-cli/src/main.rs, apps/framework-cli/src/utilities.rs, apps/framework-cli/src/utilities/isprod.rs
This reverts commit 3ffd31adaba602882a9388678103388cef851114.
The gate is not properly triggering - it is triggering in dev mode on prod
=> Revert "Add prod detection and kafka trigger avoidance. (#570)"

apps/moose-console/next.config.js
This reverts commit 0d8aadc0d4b579706264e8607924b858b25dcdf1.
=> Remove Sentry from console until we solve the CORS headers issue

apps/framework-cli/src/cli/local_webserver.rs
Existing code already handles binding to a non-localhost address via configuration file and environment variables.
For example:
```
export MOOSE_HTTP_SERVER_CONFIG__HOST=0.0.0.0
export MOOSE_HTTP_SERVER_CONFIG__PORT=4000
```
However, server output to console was hardcoded to say localhost rather than display the address passed in from the user.
=> Updated messaging to display correctly in prod

apps/framework-cli/deploy/kubernetes/moose-deployment.yaml
Final working deployment file for Kubernetes
=> updated entries - confirmed on Kubernetes cluster

apps/framework-cli/deploy/prod-load-testing/README.md, apps/framework-cli/deploy/prod-load-testing/script.js
Initial load testing setup using k6.
=> load testing related files

apps/web/src/app/components/CodeBlockCTA.tsx, apps/web/src/app/events/sendClientEvent.ts, apps/web/src/app/layout.tsx, apps/web/src/app/page.tsx, apps/web/src/app/sections/home/CTASection.tsx, apps/web/src/app/sections/home/HeroSection.tsx
Very much a useless PR since I pushed to main on accident. Sowwwy 🤦
=> Fix instrumentation

apps/framework-cli/src/cli/local_webserver.rs, apps/framework-cli/src/utilities/capture.rs
Code is unused - so commenting it to restore the release process on main
=> chore: fix broken main code

apps/framework-cli/src/cli/routines.rs
Bug fix for when there are no version folders.
Note this is WIP code that will eventually use a list of version vec in future PRs
=> handle situation when there are no version folders

apps/framework-cli/src/framework/transform.ts
This allows users to add a filter logic in their flow function so they don't have to transform every row of source data.
=> Ignore null/undefined return value from flow function

apps/framework-docs/src/pages/on-prem/configuring-moose-for-cloud.mdx, apps/framework-docs/src/pages/on-prem/deploying-on-ecs.mdx, apps/framework-docs/src/pages/on-prem/deploying-on-kubernetes.mdx, apps/framework-docs/src/pages/on-prem/packaging-moose-for-deployment.mdx
@DatGuyJonathan please review the following documentation updates relative to your review pass.
=> updates based on most recent GKE cloud deployment learnings

apps/framework-internal-app/project.toml
=> fix: internal app config

apps/framework-cli/src/cli.rs
=> Clean up error from loading project.toml

apps/moose-console/src/app/page.tsx, templates/mixplank/moose/app/datamodels/models.prisma, templates/mixplank/moose/project.toml, templates/mixplank/next/src/app/events.ts, templates/mixplank/next/src/app/funnels/page.tsx, templates/mixplank/next/src/app/insights/page.tsx, templates/mixplank/next/src/app/layout.tsx, templates/mixplank/next/src/app/nav-tabs.tsx, templates/mixplank/next/src/components/time-selector.tsx, templates/mixplank/next/src/components/time-series-form.tsx, templates/mixplank/next/src/config.ts, templates/mixplank/next/src/insights/funnel-query.ts, templates/mixplank/next/src/insights/kpi.ts, templates/mixplank/next/src/insights/model-meta.ts, templates/mixplank/next/src/insights/sessions.ts, templates/mixplank/next/src/insights/table-query.ts, templates/mixplank/next/src/insights/time-query.ts, templates/mixplank/next/src/insights/top-browsers.ts
Isolated config file, so the configuration step feels cleaner
Added nav and header
Added past 1H, better experience for demo
=> Small template improvements

apps/framework-cli/Cargo.toml
Quick fix for multiple PR colliding
=> fix: adding the feature missing for the self instrumentaion

apps/framework-docs/src/pages/on-prem/configuring-moose-for-cloud.mdx, apps/framework-docs/src/pages/on-prem/deploying-on-ecs.mdx, apps/framework-docs/src/pages/on-prem/deploying-on-kubernetes.mdx, apps/framework-docs/src/pages/on-prem/packaging-moose-for-deployment.mdx, apps/framework-docs/src/pages/on-prem/preparing-clickhouse-redpanda.mdx
Based on feedback from this Linear ticket: https://linear.app/514/issue/514-689/do-a-pass-at-qaing-the-documentation-for-packaging-a-moose-app-into-a
=> Updated based on @DatGuyJonathan peer review

apps/framework-cli/src/cli.rs, apps/framework-cli/src/cli/commands.rs, apps/framework-cli/src/cli/routines.rs, apps/framework-cli/src/cli/routines/flow.rs, apps/framework-cli/src/cli/routines/initialize.rs, apps/framework-cli/src/framework/schema/templates.rs, apps/framework-cli/src/project.rs, apps/framework-cli/src/utilities/constants.rs
Help messages & the command result:
Error cases:
=> CLI command to initialize a new flow

apps/framework-cli/src/utilities/constants.rs
Insights is currently not in use
=> chore: remove insights from the auto generated directory template

apps/framework-cli/src/cli/routines/docker_packager.rs
The internal moose app doesn't have the right prisma file, even though we've updated framework-internal-app. I suspect we copy over the moose project to the docker image, but then it runs `moose init`. The prisma file from `init` doesn't & shouldn't have the same models as the one in our internal moose app. And it overwrites the one from framework-internal-app.
=> Update docker build to not depend on moose init

apps/framework-internal-app/package.json, pnpm-lock.yaml
https://github.com/514-labs/moose/pull/785#discussion_r1546468253
=> Update cli version

apps/framework-cli/src/cli.rs, apps/framework-cli/src/cli/commands.rs, apps/framework-cli/src/cli/routines/clean.rs, apps/framework-cli/src/project.rs, apps/framework-cli/src/utilities/constants.rs
Removes Update command
Removes stop command
Refactors the clean command to stop docker and just delete the .moose folder
=> chore: remove unused commands and documnent the ones that need documentation

apps/framework-docs/src/pages/building/flows/setup.mdx
https://github.com/514-labs/moose/blob/main/apps/framework-docs/src/pages/building/data-models/_meta.json
=> Update name of ingesting data page

pnpm-lock.yaml
=> chore update pnpm lock file

apps/product-analytics/src/app/data.ts, templates/mixplank/next/src/app/data.ts
=> fix: change host environement that is already used by vercel

apps/framework-cli/src/cli.rs, apps/framework-cli/src/cli/routines/docker_packager.rs, apps/framework-cli/src/framework/transform.ts, apps/framework-cli/src/utilities/docker-compose.yml
Next step is to update `moose prod` command to run deno.
=> Use env vars for flow's redpanda conn settings

apps/framework-docs/src/pages/building/dcm/walkthrough.mdx
=> dcm doc fix

apps/framework-cli/src/cli.rs, apps/framework-cli/src/cli/routines/flow.rs, apps/framework-cli/src/framework/transform.ts
I tested the new routine locally and it started deno while listening to our internal Redpanda cluster. Will have to bump CLI version after this PR so our internal moose app has the latest changes.
=> Run flow in prod

apps/framework-internal-app/package.json, pnpm-lock.yaml
Update the cli version for internal moose app
=> Bump cli version

packages/event-capture/events/sendServerEvent.ts
Don't override data if its sent, assume if caller has included the property, they want it/ its most accurate
=> Don't override properties mixpanel data

apps/company-landing/middleware.ts, apps/framework-docs/src/middleware.ts, apps/framework-landing/middleware.ts, apps/moose-console/src/middleware.ts, apps/moose-console/tsconfig.json, pnpm-lock.yaml
Referrer is always "about:client" for NextRequest in middleware ??? Grab them from header instead
Bug abt referer in middleware
https://github.com/vercel/next.js/issues/44455
=> Fix referrer for page view

apps/framework-cli/src/cli/settings.rs, apps/framework-cli/src/utilities/capture.rs, apps/framework-docs/src/pages/building/data-models/model-data.mdx, apps/framework-internal-app/app/datamodels/models.prisma, apps/framework-internal-app/package.json, pnpm-lock.yaml
* Testing the migration in our dog food
* Adding a property to our instrumentation to distinguish between our devs and external users
=> feat: add moose_developer field

apps/framework-cli/src/utilities/git.rs
I tried to run `moose bump-version` in `framework-internal-app` and failed.
=> git actions should support repo root outside of moose

apps/framework-internal-app/package.json, apps/framework-internal-app/project.toml, pnpm-lock.yaml
Bumping version to trigger deployment in prod
=> bump version of moose in internal app

apps/framework-cli/src/infrastructure/olap/clickhouse/client.rs, apps/framework-cli/src/infrastructure/olap/clickhouse/version_sync.rs
* Adds retries with exponential backoff to clickhouse client
=> feat: implement retries with exponential backoff

apps/company-landing/app/api/event/route.ts, apps/company-landing/middleware.ts, apps/framework-docs/src/middleware.ts, apps/framework-docs/src/pages/api/event.ts, apps/framework-landing/app/api/event/route.ts, apps/framework-landing/middleware.ts, apps/moose-console/src/app/api/event/route.ts, apps/moose-console/src/middleware.ts, packages/event-capture/events/sendServerEvent.ts, pnpm-lock.yaml
Middleware, APIs and serverless functions run as lambdas on Vercel. The lack of await meant there was a race condition, leading to intermittent successes.
Secondly, page-view events don't work in preview environments with the API is returning a 401 unauthorized. It seems that API routes in preview branches are protected by vercel authentication, so I expect it to work when deployed. Though I could swear they worked before.
=> Instrumentation Fix

apps/company-landing/middleware.ts, apps/framework-docs/src/middleware.ts, apps/framework-landing/middleware.ts, apps/moose-console/src/middleware.ts, packages/event-capture/events/sendServerEvent.ts
Prevent prefetch next requests from triggering tracking middleware
=> Mixpanel dedupe page-view

apps/framework-internal-app/package.json, pnpm-lock.yaml
Should fix the internal deployment
=> chore: bump the version of the cli for the internal app

apps/framework-cli/src/cli.rs, apps/framework-cli/src/cli/routines/initialize.rs, apps/framework-cli/src/cli/routines/templates.rs
Feel free to suggest other ways of phrasing this
=> suggest next steps after moose init

apps/framework-cli/src/infrastructure/console.rs, apps/framework-cli/src/project.rs, apps/moose-console/src/app/primitives/flows/page.tsx, apps/moose-console/src/app/types.ts, apps/moose-console/src/components/overview-card.tsx, apps/moose-console/src/components/overview-list.tsx
Overview & detailed pages without flows:
------------------------------------
Overview & detailed pages with flows:
=> Show read-only list of flows in console

apps/framework-cli/src/cli.rs, apps/framework-cli/src/cli/routines/templates.rs
Using info so it's a different color & stands out more
=> Move init next steps to new line

apps/framework-cli/src/framework/aggregates.ts, apps/framework-cli/src/framework/aggregations.ts, apps/framework-cli/src/project.rs, apps/framework-cli/src/utilities/constants.rs, apps/framework-cli/src/utilities/docker-compose.yml
Implemented the workflow defined here: https://www.figma.com/file/Eyi7IU5j9uYQAXD8H79UhI/Aggregations-and-Consumption?type=whiteboard&node-id=221-509&t=JzgHLuze4IKAamAP-4
Chatted with @okane16 and started a list of next steps: https://www.figma.com/file/Eyi7IU5j9uYQAXD8H79UhI/Aggregations-and-Consumption?type=whiteboard&node-id=274-3014&t=MHoNLOAZrhvK9cwJ-4. We'll turn them into linear tickets.
=> Aggregations prototype

apps/framework-cli/src/cli/routines/dev.rs, apps/framework-cli/src/cli/routines/validate.rs, apps/framework-cli/src/utilities/constants.rs, apps/framework-cli/src/utilities/docker.rs
Hopefully makes it easier to just check one place for logs. Did it for flows, aggregations, & consumption.
=> Pipe docker logs to cli logs

apps/framework-cli/src/project/typescript_project.rs, apps/framework-docs/src/pages/moose-cli.mdx
adds another way to run moose to the package.json and document it
=> feat: add moose commands for the cli

apps/framework-cli/src/cli.rs, apps/framework-cli/src/cli/routines/flow.rs
=> Verify datamodel name on flow init

apps/company-landing/app/blog/(posts)/moose-launch/page.mdx, apps/framework-docs/src/pages/building/data-models/intro.mdx, apps/framework-docs/src/pages/building/data-models/model-data.mdx, apps/framework-docs/src/pages/building/dcm/walkthrough.mdx, apps/framework-docs/src/pages/building/flows/intro.mdx, apps/framework-docs/src/pages/building/flows/setup.mdx, apps/framework-docs/src/pages/getting-started/project-structure.mdx, apps/framework-docs/src/pages/getting-started/version-status.mdx, apps/framework-docs/src/pages/index.mdx, apps/framework-docs/theme.config.jsx
* Updates documentation to remove the mention of prisma models
* Updates the navbar to be collapsed as a default
=> docs: update documentation for TS models

apps/framework-cli/src/framework/aggregations.ts
For example, aggregation A could depend on B which depends on C which depends on the actual source table:
&nbsp;
The order in which they're created isn't guaranteed, so we retry later if they fail with a specific dependency error:
&nbsp;
=> Implement retry when creating aggregations

apps/framework-cli/src/cli/local_webserver.rs, apps/framework-cli/src/cli/routines.rs, apps/framework-cli/src/cli/routines/flow.rs, apps/framework-cli/src/cli/watcher.rs
Example of when you start dev without Foo & Bar data models defined, then we show an updated list after they define Bar:
=> Warn user if flows is missing datamodels during dev

apps/framework-cli/src/cli/routines/flow.rs, apps/framework-cli/src/framework/typescript/templates.rs
=> Add default values to flow init

pnpm-lock.yaml
Fix for having used pnpm version 9
=> rebuild lock file using pnpm 8.15.8

apps/framework-cli/Cargo.toml, apps/framework-cli/src/infrastructure/olap/clickhouse/model.rs, apps/framework-cli/src/infrastructure/olap/clickhouse/queries.rs
=> feat: standardize to UTC in the clickhouse db

apps/framework-cli/src/framework/typescript/templates.rs, apps/framework-cli/src/utilities/constants.rs
Remove Clickhouse specific query logic
=> Simpler Default Query

apps/framework-cli/src/cli/routines/docker_packager.rs
* Adds `node` to the production build
* updates the version of moose that gets embedded in the image
* Adds moose --version to be called in the build process to know which version of moose gets embedded in the image
=> fix: node not included in the production image

apps/framework-cli/src/cli/routines/flow.rs
=> Prettify flow next steps

apps/framework-cli/src/cli/routines.rs, apps/framework-cli/src/cli/routines/aggregation.rs, apps/framework-cli/src/framework/aggregations.ts, apps/framework-internal-app/app/aggregations/DailyActiveUsers.ts
Tried locally and was able to connect to prod clickhouse. Will need to bump versions after this, then monitor the deploy.
=> Add aggregations to prod

apps/framework-cli/src/cli.rs, apps/framework-cli/src/cli/local_webserver.rs, apps/framework-cli/src/cli/routines/templates.rs, apps/framework-cli/src/cli/watcher.rs, apps/framework-cli/src/framework/controller.rs, apps/framework-cli/src/framework/data_model/config.rs, apps/framework-cli/src/infrastructure/console.rs, apps/framework-cli/src/infrastructure/kafka_clickhouse_sync.rs, apps/framework-cli/src/infrastructure/olap/clickhouse/queries.rs, apps/framework-cli/src/infrastructure/olap/clickhouse/version_sync.rs, apps/moose-console/src/app/ModelView.tsx, apps/moose-console/src/app/api/console/route.ts, apps/moose-console/src/app/infrastructure/databases/[databaseName]/tables/[tableId]/page.tsx, apps/moose-console/src/app/infrastructure/databases/tables/page.tsx, apps/moose-console/src/app/primitives/models/[modelName]/page.tsx, apps/moose-console/src/app/types.ts, apps/moose-console/src/components/ingestion-points-list.tsx, apps/moose-console/src/components/overview-list.tsx, apps/moose-console/src/components/query-interface.tsx, apps/moose-console/src/components/related-infra-table.tsx, apps/moose-console/src/components/views_table.tsx, apps/moose-console/src/lib/utils.ts
* Adds `latest` to the CLI output on start
* clean up table in the Route metadata
* Add configuration to not have necessarily a table as an output to the data model
=> feat: allow data model to not have a landing table

apps/framework-cli/src/utilities/capture.rs
* Adds ip location retrieval to the data capture instrumentation
=> feat: add request about getting ip address

apps/framework-cli/src/utilities/capture.rs
=> fix versioning

apps/framework-cli/src/utilities/capture.rs
Update what the CLI is using for pushing data
=> chore: update the versioned endpoint that is used to push data

apps/framework-internal-app/package.json, pnpm-lock.yaml
=> chore: bump internal app moose version

apps/framework-cli/src/framework/transform.ts
Will rework this tomorrow because we want the cache in prod. Should do proper file watching
=> Avoid Cache in flow

apps/framework-internal-app/package.json, pnpm-lock.yaml
Update internal app to the latest version
=> update internall app

apps/framework-cli/src/cli.rs, apps/framework-cli/src/cli/routines.rs, apps/framework-cli/src/cli/routines/aggregation.rs, apps/framework-cli/src/cli/routines/flow.rs, apps/framework-cli/src/cli/routines/migrate.rs, apps/framework-cli/src/cli/watcher.rs, apps/framework-cli/src/framework/controller.rs, apps/framework-cli/src/framework/data_model/config.rs, apps/framework-cli/src/framework/flows/model.rs, apps/framework-cli/src/framework/flows/registry.rs, apps/framework-cli/src/framework/typescript/export_collectors.rs, apps/framework-cli/src/framework/typescript/flow.rs, apps/framework-cli/src/framework/typescript/ts_node.rs
In production the server was hanging and not returning to HTTP requests.
It looks like because I used the std process spawning behavior instead of the async one.
This fixed it locally for prod mode.
=> fix: remove some of the blocking behavior of flows as it was

apps/framework-internal-app/package.json, pnpm-lock.yaml
Updates the version of the internal deployment with the latest fixes
=> chore: update version of moose internal app

apps/framework-cli/Cargo.lock, apps/framework-cli/Cargo.toml, apps/framework-cli/src/cli.rs, apps/framework-cli/src/cli/routines/flow.rs, apps/framework-cli/src/framework/typescript/templates.rs
Includes not using .ts file extension in the import now that flows is in node, instead of deno.
=> Dynamic imports for flow files

apps/framework-cli/src/cli/local_webserver.rs, apps/product-analytics/public/script.js
=> Tracking patch fix

apps/framework-cli/Cargo.toml, apps/framework-cli/src/cli/local_webserver.rs, apps/framework-cli/src/cli/routines.rs, apps/framework-cli/src/framework/controller.rs, apps/framework-cli/src/infrastructure/kafka_clickhouse_sync.rs
* Fixes subscribing to topics that don't exist
* Fixes the history of optimization for views and topic creation
=> fix: version history handling

.github/workflows/release-cli.yaml, packages/ts-moose-lib/package.json, packages/ts-moose-lib/scripts/release-lib.sh, packages/ts-moose-lib/src/index.ts, packages/ts-moose-lib/tsconfig.json, packages/ts-moose-lib/tsup.config.ts, pnpm-lock.yaml
* Adds a package that we can use to host helper types and functions
The lines is mostly the ts-config
=> chore: add internal package

packages/ts-moose-lib/scripts/release-lib.sh
=> fix publishing script

packages/ts-moose-lib/package.json, packages/ts-moose-lib/src/dataModelTypes.ts, packages/ts-moose-lib/src/enumConvert.ts, packages/ts-moose-lib/src/index.ts, packages/ts-moose-lib/src/toDataModels.ts, packages/ts-moose-lib/src/typeConvert.ts, packages/ts-moose-lib/tsup.config.ts, pnpm-lock.yaml
the rust code will follow after this gets published
=> ts compiler plugin that dumps type data

apps/framework-cli/src/project/typescript_project.rs, apps/framework-internal-app/package.json, packages/ts-moose-lib/src/index.ts, pnpm-lock.yaml, templates/logs/moose/package.json, templates/product-analytics/moose/package.json
* Use the new package for moose internal dependencies
* Update all internal projects to use the new moose lib
* Add a type helper for data model config
=> chore: simplify dependencies for the user

apps/framework-cli/src/framework/typescript/ts_scripts/flow.ts, apps/framework-internal-app/project.toml
Saw a 14x improvement locally. Would like to test the dogfood app with this change.
=> Remove kafkajs tx from flows

apps/framework-cli/src/framework/typescript/ts_scripts/flow.ts, apps/framework-cli/tests/python/project/setup.py
https://github.com/514-labs/moose/assets/7286437/be6e6afb-8906-4597-8d6b-f8ac75da1004
=> Batch flows

apps/framework-cli/src/framework/typescript/ts_scripts/flow.ts
Sets a max byte size for the consumer and producer
=> fix: set max byte size for the consumer

apps/framework-docs/src/pages/building/data-models/capture-data.mdx, apps/framework-docs/src/pages/moose-cli.mdx, pnpm-lock.yaml
=> docs: update documentation

packages/ts-moose-lib/src/typeConvert.ts
* Fixes the parsing for booleans
=> fix: boolean parsing for ts parser

apps/framework-cli/src/framework/typescript/ts_scripts/flow.ts, apps/framework-docs/src/pages/building/flows/intro.mdx, apps/framework-docs/src/pages/building/flows/setup.mdx
Also updated docs to reflect this new ability.
=> Handle flow fn returning an array

apps/framework-docs/src/pages/_meta.json, apps/framework-docs/src/pages/building/data-models/model-data.mdx, apps/framework-docs/src/pages/faqs.mdx, apps/framework-docs/src/pages/quick-reference.mdx
The quick reference page is for users who already know the basics of how MooseJS works but need to refer to the docs quickly.
=> Added a new quick references page and a FAQs page

.github/workflows/release-cli.yaml
* Update the version of mac os for release
=> chore: mac os versions

.github/workflows/release-cli.yaml
* changes the design system publishing orchestration
* changes the event capture system orchestration
=> chore: change orchestration of design system release

.github/workflows/release-cli.yaml
=> fix: dependency in the release cli packages

apps/framework-cli/src/framework/core.rs, apps/framework-cli/src/framework/core/code_loader.rs, apps/framework-cli/src/framework/core/infrastructure_map.rs, apps/framework-cli/src/framework/core/primitive_map.rs, apps/framework-cli/src/framework/data_model/schema.rs, apps/framework-cli/src/framework/typescript/generator.rs, apps/framework-cli/src/framework/typescript/templates.rs
* Adds `InfrastructureMap` to have all the things to be provisioned
* Fix default app types for consumption api
=> chore: add base infrastructure for the infrastructure map

pnpm-lock.yaml, templates/product-analytics/next/package.json
accidentally deleted package.json
=> Add back deleted package.json

apps/framework-cli/src/framework/core/infrastructure_map.rs, apps/framework-cli/src/framework/core/primitive_map.rs, apps/framework-cli/src/framework/data_model/schema.rs
* Adds the algorithm to do the diff between 2 Infrastructure maps
* Remove types aliases for `TopicId` and `APIId`
=> chore: add algorithm to make the diff between 2 different infrastructure maps

apps/framework-cli/src/cli.rs, apps/framework-cli/src/cli/commands.rs, apps/framework-cli/src/cli/routines.rs, apps/framework-cli/src/cli/routines/ls.rs, apps/framework-cli/src/cli/routines/ps.rs, apps/framework-cli/src/framework/controller.rs, apps/framework-cli/src/infrastructure/olap/clickhouse.rs, apps/framework-cli/src/infrastructure/olap/clickhouse_alt_client.rs, apps/framework-cli/src/utilities/capture.rs, apps/framework-docs/src/pages/moose-cli.mdx
- Show data model, ingestion point, table, & view. Will look into topics next.
- Fix dcm bug where every version is a table
=> ls command

apps/framework-cli/src/cli/settings.rs
Adding the default value for the feature flag
=> fix: missing default value

apps/framework-cli/src/framework/flows/model.rs, apps/framework-cli/src/framework/python/flow.rs, apps/framework-cli/src/framework/python/scripts/flow_runner.py
- Handle flow returning null
- Handle flow returning array
- Set message.max.bytes
=> Bring python flows up to parity with ts flows

apps/framework-internal-app/package.json, pnpm-lock.yaml
Updates to the latest of moose to get some additional logs in production
=> chore: update version of internal app

apps/framework-cli/src/framework/controller.rs, pnpm-lock.yaml
* Adds a case where a user deactivates storage
=> fix: fix the creationg of extra topics

apps/framework-internal-app/package.json, pnpm-lock.yaml
* Bump internal version of the internal app to deploy fix
=> chore: bump internal version

apps/framework-internal-app/package.json, pnpm-lock.yaml
* FIxing the UTC error in prod
=> chore: bump moose version of internal to 0.3.454

apps/framework-cli/Cargo.lock, apps/framework-cli/Cargo.toml, apps/framework-cli/src/cli/watcher.rs
Looks like @tg339 and @phiSgr were right
This seems to fix our hanging tasks issue
=> fix: watcher hanging

apps/framework-cli/src/cli.rs, apps/framework-cli/src/cli/display.rs, apps/framework-cli/src/cli/routines.rs, apps/framework-cli/src/cli/settings.rs, apps/framework-cli/src/cli/watcher.rs, apps/framework-cli/src/framework/aggregations/registry.rs, apps/framework-cli/src/framework/core/execute.rs, apps/framework-cli/src/infrastructure/api.rs, apps/framework-cli/src/infrastructure/sync_processes.rs
* Moves the changes showing code to the `display` module
* Adds the new core to dev mode
=> Integrate `plan` with `dev` mode for data models

apps/framework-cli/src/cli.rs
Adds the npm install / pip install step to the get started instructions
=> chore: add quick install step to the introduction

apps/framework-cli/src/metrics.rs
Runs a timer from when an http request is sent to when moose responds. Then prometheus histogram observes the time and places it into buckets. As long as the obeserver number is less then the buckets limit it is put into the bucket so one number can be put into multiple buckers. This PR adds this histogram tracking for all http endpoints but condensed into one Histogram.
=> Added a Prometheus histogram to track latency across all http endpoints

apps/framework-cli/src/cli/routines/templates.rs
We didn't run CI for the previous PR.
=> fix unused import

apps/framework-cli/src/infrastructure/processes/kafka_clickhouse_sync.rs
Adds handling for null in the json data
=> fix: null handling in json

apps/framework-cli/src/cli.rs, apps/framework-cli/src/cli/commands.rs, apps/framework-cli/src/cli/routines/docker_packager.rs, apps/framework-docs/src/pages/moose-cli.mdx
=> Add build targets to cli command

apps/framework-cli/src/framework/typescript/ts_scripts/consumption-api.ts
=> fix: TS consumption api not shutting down

apps/framework-cli/src/cli/local_webserver.rs, apps/framework-cli/src/cli/routines/metrics_console/run_console/app.rs, apps/framework-cli/src/cli/routines/metrics_console/run_console/client.rs, apps/framework-cli/src/cli/routines/metrics_console/run_console/handler.rs, apps/framework-cli/src/cli/routines/metrics_console/run_console/ui.rs, apps/framework-cli/src/framework/python/scripts/streaming_function_runner.py, apps/framework-cli/src/framework/typescript/ts_scripts/streaming-function.ts, apps/framework-cli/src/metrics.rs
Tracks the number of messages in and out of each streaming function. Displays the data in a table in the ratatui ui. Also styled the ui based on the figma mockup with few changes.
Screenshot:
Overview Page:
Detailed View:
=> Measures and displays metrics from streaming functions kafka messages in and out

apps/framework-cli/src/cli/local_webserver.rs, apps/framework-cli/src/cli/routines/metrics_console/run_console.rs, apps/framework-cli/src/cli/routines/metrics_console/run_console/app.rs, apps/framework-cli/src/cli/routines/metrics_console/run_console/ui.rs
=> Added messages in and out per sec for kafka messages from streaming functions

apps/framework-cli/src/framework/core/code_loader.rs, apps/framework-cli/src/framework/core/primitive_map.rs, apps/framework-docs/src/pages/building/data-models/configuring.mdx
* adds data models to core_v2 
* Fix old docs
=> feat: add datamodel config to the core v2

apps/framework-cli/src/cli/routines/metrics_console/run_console.rs, apps/framework-cli/src/cli/routines/metrics_console/run_console/app.rs, apps/framework-cli/src/cli/routines/metrics_console/run_console/client.rs, apps/framework-cli/src/cli/routines/metrics_console/run_console/ui.rs, apps/framework-cli/src/infrastructure/processes/kafka_clickhouse_sync.rs, apps/framework-cli/src/metrics.rs
=> Added bytes per sec for kafka clickhouse sync table

apps/framework-cli/src/cli/routines/metrics_console/run_console/ui.rs
=> Styled the ratatui ui

apps/framework-cli/src/cli.rs, apps/framework-cli/src/utilities/capture.rs, apps/framework-internal-app/app/datamodels/models.ts
* Fixes the telemetry for short lived commands
* Adds telemetry for
* MigrationGeneration
* SDKgeneration
* DataModelInit
* Import
* Metrics
=> fix: short lived commands telemetry

apps/framework-cli/src/cli/routines/datamodel.rs
Add <Key> to first valid (non array, non object) field
Alphabetize Keys
Comment out types that don't resolve to useful types  such as null, empty array and empty
Much better formatting
=> Datamodel init Improvements

apps/framework-internal-app/package.json, pnpm-lock.yaml
=> chore: update internal to latest moose version

apps/framework-cli/src/infrastructure/processes/aggregations_registry.rs
Quick fix from @phiSgr that is AFK
=> fix: fix blocks reverse compatibility

apps/framework-internal-app/package.json, pnpm-lock.yaml
Updates internal so that it sends iteself its own data
=> chore: bump internal version to 531

apps/framework-cli/src/cli.rs
=> Sort --help alphabetically

apps/framework-cli/src/framework/typescript/streaming.rs, apps/framework-cli/src/framework/typescript/ts_scripts/streaming-function.ts
For now it prints:
```
Code loading TSError: ⨯ Unable to compile TypeScript:
app/functions/UserActivity__ParsedActivity.ts(11,3): error TS2741: Property 'activity' is missing in type '{ eventId: string; userId: string; timestamp: Date; }' but required in type 'ParsedActivity'.
```
=> log if import failed

apps/framework-cli/src/cli/local_webserver.rs
On the hosting side: https://github.com/514-labs/commercial/pull/76
=> Add path_prefix as env var

apps/framework-cli/src/infrastructure/stream/redpanda.rs
* Makes the replication factor configurable
=> chore: setup replication factor as something configurable

apps/framework-cli/src/infrastructure/stream/redpanda.rs, apps/framework-cli/src/project.rs
Hotfix for not requiring the replication factor in the config
=> fix: optional for replication factor

apps/framework-cli/src/cli/display.rs, apps/framework-cli/src/framework/core/infrastructure.rs, apps/framework-cli/src/framework/core/infrastructure/topic_sync_process.rs, apps/framework-cli/src/framework/core/infrastructure_map.rs, apps/framework-cli/src/infrastructure/olap/clickhouse_alt_client.rs, apps/framework-cli/src/infrastructure/processes.rs, apps/framework-cli/src/infrastructure/processes/kafka_clickhouse_sync.rs
=> sync topic to topic in core V2

apps/framework-cli/src/framework/core/infrastructure/function_process.rs, apps/framework-cli/src/infrastructure/stream/redpanda.rs
our node processes are listening to the wrong topics lol
=> add namespace filtering to fetch_topics

apps/framework-cli/src/cli/routines/ls.rs, apps/framework-cli/src/infrastructure/stream/redpanda.rs
=> Add namespace for consumer group

apps/framework-cli/src/framework/python/scripts/streaming_function_runner.py
* Fixes streaming functions logs for the python env
=> fix: fix logs for streaming functions in python

apps/framework-cli/src/infrastructure/processes/aggregations_registry.rs, apps/framework-cli/src/infrastructure/processes/process_registry.rs, apps/framework-cli/src/project.rs
* Remove the auto-creation of the `aggregations` folder which is currently confusion since we are moving away from aggregations
=> fix: remove aggregation directory creation

apps/framework-cli/src/cli.rs
Siwtches method for v2 method for check
=> fix: change docker build check for v2 method

apps/framework-cli/src/cli.rs, apps/framework-cli/src/cli/commands.rs, apps/framework-cli/src/cli/routines/docker_packager.rs, apps/framework-cli/src/utilities/docker.rs
* Adds `moose check` that will just load the project to test if all is properly aligned. This leverages corev2 functionality
* Refactors build and create docker routines out of the controller pattern
* Adds `moose check` to the build step
* Enables docker build error to be proxied to the terminal
=> feat: add moose check command

apps/framework-cli/src/framework/python/parser.rs, apps/framework-cli/tests/python/models/complex.py
=> allow user types as type param in python

apps/framework-cli/src/cli/settings.rs, apps/framework-cli/src/project.rs, apps/framework-cli/src/utilities/constants.rs
E.g. `MOOSE_LOGGER__EXPORT_TO`
=> unify environment variable format

packages/ts-moose-lib/package.json, packages/ts-moose-lib/src/commons.ts, packages/ts-moose-lib/src/consumption-helpers.ts, pnpm-lock.yaml
* Change back clickhouse client version to fix build
=> fix: change clickhouse client back to web version

apps/framework-cli/src/cli.rs, apps/framework-cli/src/cli/commands.rs, apps/framework-cli/src/cli/logger.rs, apps/framework-cli/src/cli/settings.rs, apps/framework-cli/src/metrics.rs, apps/framework-cli/src/utilities.rs, apps/framework-cli/src/utilities/decode_object.rs
Use configurable endpoint and added fields
=> Dynamic Logs/Metrics

apps/framework-cli/src/cli/routines/docker_packager.rs, apps/framework-cli/src/framework/typescript/generator.rs, apps/framework-cli/src/framework/typescript/parser.rs, apps/framework-cli/src/metrics.rs, apps/framework-cli/src/project.rs, apps/framework-cli/src/utilities/constants.rs
scripts depend on tsconfig to compile correctly
=> include tsconfig in built docker image

apps/framework-cli/src/framework/python/scripts/streaming_function_runner.py, apps/framework-cli/src/framework/python/templates.rs, apps/framework-cli/src/framework/streaming/generate.rs, apps/framework-cli/src/project/python_project.rs, apps/framework-cli/tests/python/project/setup.py, packages/py-moose-lib/moose_lib/__init__.py, packages/py-moose-lib/moose_lib/main.py
- Adds moosepy lib to default python project
- Adds Key to lib and use it in default project
- Adds StreamingFunction to lib and use it in default project
=> Add streaming function to moosepy

apps/framework-cli/src/framework/python/templates.rs, packages/py-moose-lib/moose_lib/__init__.py, packages/py-moose-lib/moose_lib/blocks.py, packages/py-moose-lib/moose_lib/commons.py, packages/py-moose-lib/moose_lib/main.py
- Adds blocks to lib and use it in default project
- Adds MooseClient to consumption api example
- Adds cliLog to lib. Can be used like this:
```
from moose_lib import cli_log, CliLogData
log_data = CliLogData(action="UserLogin", message="User has logged in successfully.")
cli_log(log_data)
```
=> Add blocks to moosepy

apps/framework-cli/src/cli/local_webserver.rs, apps/framework-cli/src/cli/routines.rs, apps/framework-cli/src/cli/watcher.rs, apps/framework-cli/src/framework/consumption.rs, apps/framework-cli/src/framework/consumption/loader.rs, apps/framework-cli/src/framework/consumption/model.rs, apps/framework-cli/src/framework/controller.rs, apps/framework-cli/src/framework/core/infrastructure/api_endpoint.rs, apps/framework-cli/src/framework/core/infrastructure_map.rs, apps/framework-cli/src/framework/core/primitive_map.rs, apps/framework-cli/src/framework/data_model/config.rs
Fixes consumptions apis with core v2
=> fix: corev2 and consumption apis

apps/framework-cli/src/cli/routines/datamodel.rs, apps/framework-cli/src/framework/core/code_loader.rs, apps/framework-cli/src/framework/core/primitive_map.rs, apps/framework-cli/src/framework/data_model/config.rs, apps/framework-cli/src/framework/data_model/parser.rs, apps/framework-cli/src/framework/python/executor.rs, apps/framework-cli/src/framework/python/templates.rs, apps/framework-cli/tests/python/models/complex.py, apps/framework-cli/tests/python/models/simple.py, packages/py-moose-lib/moose_lib/main.py
=> Python data model decorator

apps/framework-cli/src/cli/routines/consumption.rs, apps/framework-cli/src/framework/python/scripts/blocks_runner.py, apps/framework-cli/src/framework/python/scripts/streaming_function_runner.py, apps/framework-cli/src/framework/python/templates.rs, apps/framework-cli/src/framework/typescript/templates.rs, packages/ts-moose-lib/src/blocks/runner.ts, packages/ts-moose-lib/src/streaming-functions/runner.ts
Also adds consumption init for python
=> Surface errors from python runners

apps/framework-docs/src/pages/data-models/init-model.mdx, apps/framework-landing/app/nav.tsx, apps/framework-landing/app/sections/FooterSection.tsx
- fix mobile nav
- add footer
- fix docs create data model formatting
=> Moose landing hotfix

apps/framework-cli/src/cli.rs, apps/framework-cli/src/cli/routines/initialize.rs, apps/framework-cli/src/framework/typescript/templates.rs, apps/framework-cli/src/project.rs
don't include python stuff in vscode settings in ts proj
=> create tsconfig even if --empty flag is used

apps/framework-cli/src/cli/routines/docker_packager.rs, apps/framework-cli/src/framework/typescript/bin.rs, apps/framework-cli/src/framework/typescript/parser.rs
* fixes finding the path for moose versions
=> fix: ts version bin location finder

apps/framework-cli/src/cli/local_webserver.rs
an unpushed change in previous PR
do we want this behind a flag?
=> include error message in HTTP response

apps/framework-cli/src/infrastructure/olap/clickhouse/queries.rs
* Fixes escape chars in field names
* Removes HTML escaping from handlebars templates
* Fixes order by statement when multiple order bys are present
* Replaces " by ` that makes the query more readable in the logs when debugging
=> fix: escaping of characters for field names

apps/framework-cli/src/cli/routines.rs, apps/framework-cli/src/infrastructure/redis/redis_client.rs
Update RedisClient to support named resource locks and to externalize the leadership lock functionality.
=> RedisClient named resource locks support

apps/framework-cli/src/framework/languages.rs
Small update to enable `ts` and `py` to be options
=> chore: update init script

apps/framework-cli/src/framework/typescript/generator.rs
=> ignore JWT fields in ingest SDK generation

Cargo.lock, apps/framework-cli/Cargo.toml, apps/framework-cli/src/cli.rs, apps/framework-cli/src/framework/core.rs, apps/framework-cli/src/framework/core/check.rs, apps/framework-cli/src/framework/python.rs, apps/framework-cli/src/framework/python/checker.rs, apps/framework-cli/src/framework/python/executor.rs, apps/framework-cli/src/framework/python/utils.rs, apps/framework-cli/src/framework/typescript.rs, apps/framework-cli/src/framework/typescript/checker.rs
For example, if I have a lower version than required:
=> Check python version

apps/framework-cli/src/cli.rs, apps/framework-cli/src/cli/commands.rs, apps/framework-cli/src/cli/routines/docker_packager.rs
this is when the moose-cli has the moose-lib
=> move write infra map to check

apps/framework-cli/src/framework/python/scripts/streaming_function_runner.py
So in the streaming function, we can do something like `activity.child.value` instead of `activity.child['value']`
=> deserialize nested for python streaming function

apps/framework-cli/src/framework/core/infrastructure_map.rs, apps/framework-cli/src/framework/core/plan.rs
not sure if this is the best place to add the prefixes
=> infra map with topic prefix

apps/framework-cli/src/framework/python/scripts/consumption_runner.py, packages/ts-moose-lib/src/consumption-apis/runner.ts
=> feat: add logs to consumption api for ts

apps/framework-cli/src/cli/local_webserver.rs, apps/framework-cli/src/metrics.rs
Fixes the metrics console on the latest version
=> fix: metrics console back up

apps/framework-cli/src/infrastructure/olap/clickhouse/queries.rs
=> backticks around each field

apps/framework-cli/src/utilities/validate_passthrough.rs
Not sure how needed/useful this is.
=> accept float unix timestamp

apps/framework-cli/src/infrastructure/olap/clickhouse.rs
Fix for:
```
[2024-10-28T23:01:14Z INFO a078960d-d441-45a8-a7e9-c83d246ae4a8 - moose_cli::infrastructure::olap::clickhouse] Updating table: "RawSessionActivity_0_0"
[2024-10-28T23:01:15Z INFO a078960d-d441-45a8-a7e9-c83d246ae4a8 - moose_cli::infrastructure::olap::clickhouse] Updating table: "SessionActivity_0_0"
Prod Failed to start production mode: Failed to communicate with Olap DB
Caused by:
0: Failed to execute the changes on Clickhouse
1: Error interacting with Clickhouse
2: bad response: Code: 517. DB::Exception: Metadata on replica is not up to date with common metadata in Zookeeper. It means that this replica still not applied some of previous alters. Probably too many alters executing concurrently (highly not recommended). You can retry this error. (CANNOT_ASSIGN_ALTER) (version …
```
=> retry alter statements

apps/framework-cli/src/cli/local_webserver.rs, apps/framework-cli/src/framework/python/scripts/streaming_function_runner.py, apps/framework-cli/src/infrastructure/olap/clickhouse/client.rs, apps/framework-cli/src/infrastructure/olap/clickhouse/inserter.rs, apps/framework-cli/src/infrastructure/processes/kafka_clickhouse_sync.rs, apps/framework-cli/src/infrastructure/stream/redpanda.rs
* Adds at least once delivery
* Adds tests for the inserter
=> At least once delivery for Kafka <> Clickhouse sync

packages/ts-moose-lib/src/streaming-functions/runner.ts
in a huge batch, we may send thousands of concurrent requests to neon.
=> limit concurrency to 100 in js streamming function runner

apps/framework-cli/src/framework/core/infrastructure_map.rs, packages/ts-moose-lib/src/streaming-functions/runner.ts
Fixing `TypeError: May not write null values to stream`
=> fix parallel map and handle input only func in runner

Cargo.lock, apps/framework-cli/Cargo.toml, apps/framework-cli/src/cli/local_webserver.rs, apps/framework-cli/src/main.rs, packages/ts-moose-lib/package.json, packages/ts-moose-lib/src/consumption-apis/runner.ts, packages/ts-moose-lib/src/instrumentation.ts, packages/ts-moose-lib/src/moose-runner.ts, pnpm-lock.yaml
* Add instrumentation to get trace data from the consumption api
=> chore: instrument spans for time spent in consumption api

apps/framework-cli-load-test/script.js, apps/framework-cli/src/cli/local_webserver.rs
Change the client to be reusable so that we reuse connections to the consumption web server
=> fix: add consumption client reuse

apps/framework-landing/app/nav.tsx, apps/framework-landing/app/page.tsx, apps/framework-landing/app/sections/home/HeroSection.tsx, apps/framework-landing/app/sections/home/HostWithBorealSection.tsx
=> Moose hero

apps/framework-cli/src/cli/routines.rs, apps/framework-cli/src/infrastructure/redis/redis_client.rs
Both commands (SET NX and EXPIRE) are executed in a single atomic transaction. There's no possibility of another process interfering between the two operations
=> Atomic pairing for SET NX and EXPIRE on resource locks

apps/framework-cli/src/cli/routines.rs, apps/framework-cli/src/infrastructure/redis/redis_client.rs
The key updates are:
* Update the atomic lock handling with regards to setting expiration
* Detailed logging of lock management errors
* Tracking both whether we have the lock (has_lock) and whether we just acquired it (is_new_acquisition)
* Only execute the leadership tasks if we both have the lock AND just acquired it (is_new_acquisition)
* In the renewal case, maintain the lock but won't trigger leadership tasks again
Tested with local multi-moose and lock handing between processes.
=> Improved handling of redis-based leadership lock

apps/framework-cli/src/cli/routines.rs, apps/framework-cli/src/infrastructure/redis/redis_client.rs
This PR leverages Redis Lua scripts to ensure atomic operations on lock related functionality.
=> further improvements to leadership lock management

packages/ts-moose-lib/src/streaming-functions/runner.ts
Adds some buffer for the consumption of messages and batching them to kafka
=> fix: add some buffer to the computation for message max size

packages/ts-moose-lib/src/streaming-functions/runner.ts
=> dummty-change

apps/framework-docs/src/pages/data-models/init-model.mdx
What type of data is an input to init?
=> Update init-model.mdx with detail

apps/framework-cli/src/infrastructure/olap/clickhouse.rs
Quick docs update to redeploy new version
=> docs: add function docs to trigger a redeploy

apps/framework-cli/src/infrastructure/redis/redis_client.rs
=> simplify channel name

.github/workflows/release-cli.yaml
Adds resources to release to accelerate release
=> chore: bump version and resources for release build

apps/framework-cli/pyproject.toml
Bumps the target version of the build for mac os
=> fix: bump version of release maturin

apps/framework-cli/src/cli/logger.rs
=> fix: optional export to logger configuration

apps/framework-cli/src/cli/display.rs, apps/framework-cli/src/cli/routines/logs.rs, apps/framework-cli/src/cli/routines/peek.rs
Output primitive changes, peek, & terminal messages to log file
=> log changes

apps/framework-cli/src/infrastructure/stream/redpanda.rs
Fixes topic creation - not sure how we missed this for the past 2 weeks
=> fix: topic creation

Cargo.lock, apps/framework-cli/Cargo.toml, apps/framework-cli/src/cli/local_webserver.rs, apps/framework-cli/src/cli/routines.rs, apps/framework-cli/src/cli/routines/openapi.rs, apps/framework-cli/src/cli/watcher.rs, apps/framework-cli/src/framework/consumption/model.rs, apps/framework-cli/src/framework/core/infrastructure/api_endpoint.rs, apps/framework-cli/src/framework/core/infrastructure_map.rs, apps/framework-cli/src/utilities/constants.rs
Generates openapi spec when starting local webserver, & refreshes it during file watcher mode.
https://github.com/user-attachments/assets/5401e359-ed67-4a38-b77e-c6e007ccdbd2
TBD:
- egress for typescript. dependent on the typia integration
=> openapi ingress (ts, py) & egress (py)

apps/framework-cli/src/infrastructure/olap/clickhouse/inserter.rs
This pull request includes several changes to improve logging and track additional metrics in the `Inserter` implementation for ClickHouse. The most important changes include adding a new field to the `Batch` struct, updating log levels, and enhancing log messages to include more detailed information.
Enhancements to logging and metrics:
* [`apps/framework-cli/src/infrastructure/olap/clickhouse/inserter.rs`](diffhunk://#diff-15f02b314e130778bd56d81e964452d161d74a8dcf48bb70f8e795b936e4daa2L7-R7): Updated log levels from `error` to `warn` to better reflect the severity of issues during offset commits and insert operations. [[1]](diffhunk://#diff-15f02b314e130778bd56d81e964452d161d74a8dcf48bb70f8e795b936e4daa2L7-R7) [[2]](diffhunk://#diff-15f02b314e130778bd56d81e964452d161d74a8dcf48bb70f8e795 …
=> chore: improve logging of the sync process

apps/framework-cli/src/framework/python/scripts_worker.rs, apps/framework-cli/src/framework/python/wrappers/scripts/python_worker_wrapper/logging.py, apps/framework-cli/src/framework/python/wrappers/scripts/python_worker_wrapper/workflow.py, packages/py-moose-lib/moose_lib/commons.py, packages/py-moose-lib/moose_lib/tasks.py
=> scripts logger

apps/framework-cli/src/cli.rs, apps/framework-cli/src/cli/commands.rs, apps/framework-cli/src/cli/routines/scripts.rs, apps/framework-cli/src/framework/python/executor.rs, apps/framework-cli/src/framework/python/wrappers/consumption_runner.py, apps/framework-cli/src/framework/scripts.rs, apps/framework-cli/src/framework/scripts/executor.rs, packages/py-moose-lib/moose_lib/main.py, packages/py-moose-lib/setup.py
=> trigger workflow from api

apps/framework-cli/src/cli/routines/openapi.rs
Mostly refactor, main change is in `build_schema` function
https://github.com/user-attachments/assets/9f27c1da-3711-45e2-82df-49c55eea394f
=> fix openapi schema for nested objects

apps/framework-cli/src/cli/watcher.rs
https://github.com/user-attachments/assets/7187d27a-29fb-4a1b-b133-6e9fdf499c91
=> add workflows to filewatcher

apps/framework-cli/src/framework/python/scripts_worker.rs, apps/framework-cli/src/framework/python/wrappers/consumption_runner.py, apps/framework-cli/src/framework/python/wrappers/scripts/python_worker_wrapper/activity.py, apps/framework-cli/src/framework/python/wrappers/scripts/python_worker_wrapper/serialization.py, apps/framework-cli/src/framework/python/wrappers/scripts/python_worker_wrapper/types.py, apps/framework-cli/src/framework/python/wrappers/scripts/python_worker_wrapper/worker.py, apps/framework-cli/src/framework/python/wrappers/scripts/python_worker_wrapper/workflow.py, packages/py-moose-lib/moose_lib/tasks.py
This pull request introduces several changes to improve the functionality and robustness of the Python worker and workflow execution within the framework CLI. The most important changes include adding new files for serialization and types, updating workflow and activity handling, and enhancing logging for better traceability.
* [`apps/framework-cli/src/framework/python/wrappers/scripts/python_worker_wrapper/serialization.py`](diffhunk://#diff-1b255c1f95f13543f3c6e4f0f17df5da229a7c37f64298d4a725e851b1f21b28R1-R50): Added a custom JSON encoder (`MooseJSONEncoder`) and decoder (`moose_json_decode`) to handle common Python types.
* [`apps/framework-cli/src/framework/python/wrappers/scripts/python_worker_wrapper/types.py`](diffhunk://#diff-cb23de9383a01dd77963b7d2835a5d49cce6eedfd983a451c9fdb08 …
=> WIP - data passing for workflows

apps/framework-cli/src/cli/local_webserver.rs
This pull request includes several improvements to the `async fn ingest_route` function in the `apps/framework-cli/src/cli/local_webserver.rs` file. The changes enhance the logging and route matching functionality.
Enhancements to logging:
* Added debug logs to display the route being searched and the available routes in the route table.
Improvements to route matching:
* Modified the route matching logic to be case-insensitive by converting both the route and the keys in the route table to lowercase before comparison.
Other improvements:
* Updated the log message for missing routes to include the list of available routes when in non-production mode.
=> fix for case sensitivity

.vscode/tasks.json, apps/framework-cli/src/framework/python/wrappers/consumption_runner.py, apps/framework-cli/src/framework/typescript/templates.rs, packages/ts-moose-lib/src/scripts/activity.ts, packages/ts-moose-lib/src/scripts/task.ts
=> pass data to ts workflow tasks

apps/framework-cli/src/framework/python/templates.rs, apps/framework-cli/src/framework/python/wrappers/scripts/python_worker_wrapper/activity.py, apps/framework-cli/src/infrastructure/olap/clickhouse/inserter.rs
=> pass input data directly to py workflow

apps/framework-cli/src/infrastructure/redis/leadership.rs, apps/framework-cli/src/infrastructure/redis/redis_client.rs
Updated the Lua script for lock expiration to enhance clarity and functionality. Modified the check_and_renew_lock method in RedisClient to streamline lock acquisition and renewal process.
=> Update Redis leadership lock renewal logic and improve logging

apps/framework-cli/src/framework/typescript/bin.rs, apps/framework-cli/src/framework/typescript/blocks.rs, apps/framework-cli/src/framework/typescript/consumption.rs, apps/framework-cli/src/framework/typescript/scripts_worker.rs, apps/framework-cli/src/framework/typescript/streaming.rs, packages/ts-moose-lib/package.json, packages/ts-moose-lib/src/blocks/runner.ts, packages/ts-moose-lib/src/consumption-apis/exportTypeSerializer.ts, packages/ts-moose-lib/src/consumption-apis/runner.ts, packages/ts-moose-lib/src/moduleExportSerializer.ts, packages/ts-moose-lib/src/moose-runner.ts, packages/ts-moose-lib/src/scripts/runner.ts, packages/ts-moose-lib/src/streaming-functions/runner.ts, pnpm-lock.yaml
This pull request includes multiple changes to improve the configuration management and argument handling in various parts of the codebase, particularly in the `framework-cli` and `ts-moose-lib` packages. The most important changes include refactoring argument handling to use more structured configurations, enhancing SSL and JWT handling, and updating dependencies.
* [`apps/framework-cli/src/framework/typescript/bin.rs`](diffhunk://#diff-512f9056d7fb79fe06c87b8e997eba0321a5a4f00f99f76929f595dcc5038d54L28-R30): Reordered the `bin_path` format to ensure `node_modules/.bin` is prioritized.
* [`apps/framework-cli/src/framework/typescript/blocks.rs`](diffhunk://#diff-b4b5b30987d6d4d4c9b217ecdf9e00905435bd890fe08a09d18d7867a1c33123L21-R34): Refactored argument handling to use a mutable vector …
=> fix: streaming dmv1 functions with dmv2

apps/framework-cli/src/framework/python/consumption.rs, apps/framework-cli/src/framework/python/executor.rs, apps/framework-cli/src/framework/python/wrappers/consumption_runner.py, packages/py-moose-lib/moose_lib/dmv2.py, packages/py-moose-lib/moose_lib/internal.py, packages/py-moose-lib/moose_lib/query_param.py
Edit:
Hm, not sure about these test failures. They passed when I pushed the branch https://github.com/514-labs/moose/actions/runs/14113075568, then I rebased and it started failing.
=> python dmv2 consumptionapi

apps/framework-cli/src/cli/routines/openapi.rs, apps/framework-cli/src/framework/core/infrastructure_map.rs, apps/framework-cli/src/framework/python/wrappers/consumption_runner.py, packages/py-moose-lib/moose_lib/dmv2.py, packages/py-moose-lib/moose_lib/internal.py, packages/py-moose-lib/moose_lib/main.py, packages/ts-moose-lib/src/consumption-apis/typiaValidation.ts, packages/ts-moose-lib/src/dmv2/dataModelMetadata.ts, packages/ts-moose-lib/src/dmv2/index.ts, packages/ts-moose-lib/src/dmv2/internal.ts
TS example:
```
interface UserEvent {
userId: Key<string>;
username: string;
}
export const UserEventPipeline = new IngestPipeline<UserEvent>("UserEvent", {
table: true,
stream: true,
ingest: true,
});
interface QueryParams {
limit?: number & tags.Type<"int32"> & tags.Minimum<1> & tags.Maximum<1000>;
}
interface ResponseType {
events: UserEvent[];
count: number;
}
export const UserEventEgress = new ConsumptionApi<QueryParams, ResponseType>(
"getUserEvents",
async ({ limit = 5 }, { client, sql }) => {
const result = await client.query.execute(sql`SELECT * FROM UserEvent LIMIT ${limit}`);
const resultJson = await result.json() as UserEvent[];
return {
events: resultJson,
count: resultJson.length,
}
}
);
```
Py example:
```
IngestPipeline[UserEvent]("UserEvent", DataModelConfigV2())
class …
```
=> openapi dmv2

apps/framework-cli/src/framework/core/infrastructure/table.rs
=> Proto dedup

apps/framework-cli/src/framework/python/wrappers/consumption_runner.py, packages/py-moose-lib/moose_lib/blocks.py, packages/py-moose-lib/moose_lib/data_models.py, packages/py-moose-lib/moose_lib/dmv2.py, packages/py-moose-lib/moose_lib/internal.py, packages/ts-moose-lib/src/consumption-apis/helpers.ts
```py
class Stuff(BaseModel):
date_time: datetime
users: Aggregated[int, AggregateFunction(agg_func="uniq", param_types=[str])]
pages: Aggregated[int, AggregateFunction(agg_func="uniq", param_types=[str])]
updates: Aggregated[int, AggregateFunction(agg_func="sum", param_types=[int])]
class RawEvent(BaseModel):
date_time: Key[datetime]
title_url: str
topic: str
user: str
OlapTable[RawEvent]("rawEvents")
MaterializedView[Stuff](MaterializedViewOptions(
select_statement="""SELECT toStartOfMinute(date_time) AS dateTime,
uniqState(user) as users,
uniqState(title_url) as pages,
sumState(toInt64(1)) AS updates
FROM rawEvents
GROUP BY date_time""",
table_name="byMinute",
materialized_view_name="byMinute_mv",
engine=ClickHouseEngines.AggregatingMergeTree,
order_by_fields=["date_time"],
))
```
=> Python DMv2 Materialized View

packages/ts-moose-lib/src/dataModels/typeConvert.ts
handling stuff like `number & typia.tags.Type<"int64"> & typia.tags.Maximum<100>`
in the previous naive approach, the type was `value?: "int64" & 100`, so it's always undefined.
=> handle multiple typia tags

apps/framework-docs/src/pages/aurora/host_setup.md
issue with claude launch no longer exists
=> Update host_setup.md -> claude launch

apps/framework-cli/src/cli/local_webserver.rs, apps/framework-cli/src/framework/core/execute.rs, apps/framework-cli/src/framework/core/infrastructure_map.rs, apps/framework-cli/src/infrastructure/processes.rs, apps/framework-cli/src/infrastructure/processes/functions_registry.rs, apps/framework-cli/src/infrastructure/processes/kafka_clickhouse_sync.rs, packages/ts-moose-lib/src/dmv2/internal.ts, packages/ts-moose-lib/src/streaming-functions/runner.ts
This pull request includes several changes to improve error handling, enhance functionality, and ensure proper configuration validation in the `framework-cli` and `ts-moose-lib` packages. The most important changes are grouped into error handling improvements, functionality enhancements, and configuration validation.
Error Handling Improvements:
* Added a new `InfraMapError` enum to handle errors when accessing components in the infrastructure map, such as missing topics or tables. (`apps/framework-cli/src/framework/core/infrastructure_map.rs`, `[apps/framework-cli/src/infrastructure/processes.rsR45-R54](diffhunk://#diff-2ee8aa9926aa305775c85047133ad9c35bf6140f6885f235ed98fa3426f94699R45-R54)`)
* Updated methods in `InfrastructureMap` to use `InfraMapError` for better error reporting. …
=> fix: streaming with namespace with dmv2

apps/framework-docs/src/pages/aurora/index.mdx
=> Update aurora documentation.mdx

.github/workflows/test-framework-cli.yaml
This pull request includes updates to the GitHub Actions workflow to improve the process of detecting changes and running tests. The most important changes focus on enhancing the accuracy of change detection and providing better visibility into the files being checked.
Enhancements to change detection and visibility:
* [`.github/workflows/test-framework-cli.yaml`](diffhunk://#diff-3b823426133c426c409ab0bec8905fb58185ad27ffa6c316b5e2fc9c7d86ef16R27-R31): Added fetching of tags and the main branch to ensure the latest changes are considered.
* [`.github/workflows/test-framework-cli.yaml`](diffhunk://#diff-3b823426133c426c409ab0bec8905fb58185ad27ffa6c316b5e2fc9c7d86ef16L45-R70): Modified the command to get changed files between the main branch and the current branch, and added grouped output …
=> fix comparison function

.github/workflows/test-framework-cli.yaml, packages/ts-moose-lib/src/scripts/runner.ts
This pull request includes changes to the `runScripts` function in the `packages/ts-moose-lib/src/scripts/runner.ts` file to improve logging and process handling. The most important changes include updating log messages to be more consistent and modifying the shutdown process to ensure proper exit codes.
Improvements to logging:
* Updated log messages to use `[SHUTDOWN]` instead of `[PROCESS]` for clarity. [[1]](diffhunk://#diff-8e3371c660e1eab4181d14ae070096888376a75670ecd7d69d93dc78f8b88a97R226-L249) [[2]](diffhunk://#diff-8e3371c660e1eab4181d14ae070096888376a75670ecd7d69d93dc78f8b88a97L258-R276)
Improvements to process handling:
* Changed the behavior when no scripts are found to register, replacing `return null` with `process.exit(0)` to ensure the process exits cleanly.
* Simplified …
=> fix exiting when no workflows

.github/workflows/test-framework-cli.yaml, apps/framework-cli/src/cli/routines/templates.rs
=> call package-templates.js in the test that depends on it

apps/framework-cli/src/framework/core/infrastructure_map.rs, apps/framework-cli/src/framework/core/mod.rs, apps/framework-cli/src/framework/core/partial_infrastructure_map.rs, apps/framework-cli/src/framework/python/datamodel_config.rs
* I moved the partial infra map to its own module
* Added some tests in the diff algorithm
* Rewrote the column difference algorithm to go from O(n^2) on the number of columns to O(n)
=> chore: add some tests for the table diff algorithm

apps/framework-cli/src/framework/core/infrastructure_map.rs
Adds tests for the diffing algorithm
=> chore: add tests on the diff algorithm for all missing objects

apps/framework-cli/src/cli/routines.rs, apps/framework-cli/src/cli/watcher.rs, apps/framework-cli/src/framework/core/infrastructure/topic.rs, apps/framework-cli/src/framework/core/plan.rs, packages/protobuf/infrastructure_map.proto
Found a small issue where the version in the proto infra should have been optional
=> feat: make the version field optional for Topic in the proto

apps/framework-cli/src/framework/core/infrastructure/api_endpoint.rs, apps/framework-cli/src/framework/core/infrastructure/function_process.rs, apps/framework-cli/src/framework/core/infrastructure/table.rs, apps/framework-cli/src/framework/core/infrastructure/topic_sync_process.rs, apps/framework-cli/src/framework/core/infrastructure_map.rs, apps/framework-cli/src/framework/core/partial_infrastructure_map.rs, apps/framework-cli/src/framework/streaming/loader.rs, apps/framework-cli/src/framework/streaming/model.rs, packages/protobuf/infrastructure_map.proto
=> fix: proto make optional what needs to be optional

apps/framework-docs/src/components/language-switcher.tsx, apps/framework-docs/src/components/product-badge.tsx
Branch for various docs post launch UI polish.
This one tries to make the lang switcher sticky so its always available.
=> Docs UI polish - Sticky Lang Switcher

Cargo.lock, packages/posthog514client-rs/Cargo.toml, packages/posthog514client-rs/README.md, packages/posthog514client-rs/src/blocking.rs, packages/posthog514client-rs/src/client.rs, packages/posthog514client-rs/src/event.rs, packages/posthog514client-rs/src/lib.rs, packages/posthog514client-rs/tests/blocking_integration_tests.rs
Updated posthog514client-rs to support non-async usage as required by Aurora
=> Update posthog514client-rs 

apps/framework-cli/src/cli/local_webserver.rs, apps/framework-cli/src/infrastructure/stream/kafka/client.rs
checks availability of redis, redpanda, and clickhouse
=> 514NEW-102: enhanced the health check endpoint

apps/framework-cli/src/cli/routines/docker_packager.rs
**fix: copy python requirements.txt and install them**
=> mitchell/fix-python: builds

apps/framework-docs/src/pages/moose/building/materialized-views.mdx
updates aggregated type info for python
=> mv docs fix

apps/framework-docs/src/pages/moose/building/materialized-views.mdx
Update the docs based on the current version of the api
=> docs: update materialized views api

templates/ads-b-frontend/template.config.toml, templates/ads-b/template.config.toml, templates/github-dev-trends/template.config.toml, templates/goodreads/template.config.toml, templates/live-heartrate-leaderboard/template.config.toml, templates/next-app-empty/template.config.toml, templates/python-empty/template.config.toml, templates/python/template.config.toml, templates/typescript-empty/template.config.toml, templates/typescript/template.config.toml
This pull request introduces a consistent addition of telemetry configuration to multiple template configuration files. The change ensures that telemetry is enabled comprehensively across all templates.
* Added `enable_telemetry="comprehensive"` to the following template configuration files:
- `templates/ads-b-frontend/template.config.toml`
- `templates/ads-b/template.config.toml`
- `templates/github-dev-trends/template.config.toml`
- `templates/goodreads/template.config.toml`
- `templates/live-heartrate-leaderboard/template.config.toml`
- `templates/next-app-empty/template.config.toml`
- `templates/python-empty/template.config.toml`
- `templates/python/template.config.toml`
- `templates/typescript-empty/template.config.toml`
- `templates/typescript/template.config.toml`
=> add enable_telemetry key to all template.config.toml files.

.prettierrc, apps/framework-cli-e2e/test/templates.test.ts, apps/framework-docs/src/components/callout.tsx, apps/framework-docs/src/components/cta-card.tsx, apps/framework-docs/src/components/language-wrappers.tsx, apps/framework-docs/src/components/zoom-img.tsx, apps/framework-internal-app/app/apis/log_query.ts, packages/design-system-components/components/base-nav.tsx, packages/design-system-components/components/icon-cards.tsx, packages/design-system-components/components/trackable-components.tsx, packages/event-capture/events/sendServerEvent.ts, packages/ts-moose-lib/src/consumption-apis/helpers.ts, packages/ts-moose-lib/src/consumption-apis/runner.ts, packages/ts-moose-lib/src/consumption-apis/typiaValidation.ts, packages/ts-moose-lib/src/dataModels/enumConvert.ts, packages/ts-moose-lib/src/dataModels/toDataModels.ts, packages/ts-moose-lib/src/dataModels/typeConvert.ts, packages/ts-moose-lib/src/dataModels/types.ts, packages/ts-moose-lib/src/dmv2/dataModelMetadata.ts, packages/ts-moose-lib/src/dmv2/internal.ts, packages/ts-moose-lib/src/moose-runner.ts, packages/ts-moose-lib/src/streaming-functions/runner.ts
=> turn on prettier's experimentalTernaries

apps/framework-cli/src/cli/local_webserver.rs, apps/framework-cli/src/framework/core/infra_reality_checker.rs, apps/framework-cli/src/framework/core/infrastructure/api_endpoint.rs, apps/framework-cli/src/framework/core/infrastructure/function_process.rs, apps/framework-cli/src/framework/core/infrastructure/table.rs, apps/framework-cli/src/framework/core/infrastructure/topic.rs, apps/framework-cli/src/framework/core/infrastructure_map.rs, apps/framework-cli/src/framework/core/partial_infrastructure_map.rs, apps/framework-cli/src/framework/data_model/config.rs, apps/framework-cli/src/framework/data_model/model.rs, apps/framework-cli/src/infrastructure/olap/clickhouse.rs, apps/framework-cli/src/infrastructure/olap/ddl_ordering.rs, packages/protobuf/infrastructure_map.proto, packages/py-moose-lib/moose_lib/dmv2.py, packages/py-moose-lib/moose_lib/internal.py, packages/ts-moose-lib/src/dmv2/index.ts, packages/ts-moose-lib/src/dmv2/internal.ts, pnpm-lock.yaml
=> Add Metadata map to propagate to infra map -- Python and TS

apps/framework-docs/src/pages/index.mdx, apps/framework-docs/src/pages/moose/building/data-modeling.mdx, apps/framework-docs/src/pages/moose/building/streams.mdx, apps/framework-docs/src/pages/moose/getting-started/quickstart.mdx, templates/github-dev-trends/Readme.md
type docs updates for new types
fan in and out for streaming
fix broken link in data modeling footer
=> Lowcardinality

apps/framework-cli/src/cli/local_webserver.rs
Still seeing cors error. The options request is asking for these: `access-control-request-headers: authorization,traceparent,tracestate`
=> fix cors #2

apps/framework-cli/src/framework/python/generate.rs, packages/py-moose-lib/moose_lib/data_models.py
https://docs.pydantic.dev/latest/concepts/models/#private-model-attributes
=> map python field names starting with _

apps/framework-cli/src/cli/routines/templates.rs, templates/ads-b-frontend/template.config.toml, templates/ads-b/template.config.toml, templates/next-app-empty/template.config.toml, templates/python-empty/template.config.toml, templates/typescript-empty/template.config.toml, templates/typescript/template.config.toml
This pull request updates the `description` field in the configuration files for various project templates to provide more descriptive and accurate summaries. The changes aim to improve clarity and consistency across template descriptions.
Template description updates:
* [`templates/ads-b-frontend/template.config.toml`](diffhunk://#diff-367d1a210861c8b9cfb3faea14e5b96f968c5b2a9d9755b41c6ed03bfcf38decL2-R2): Updated the `description` to "Realtime aircraft transponder data, with a frontend."
* [`templates/ads-b/template.config.toml`](diffhunk://#diff-21a41d185429ce239ca59235bbace178888e0401a8f56e81245853c92123c853L2-R2): Updated the `description` to "Real time aircraft transponder data."
* [`templates/next-app-empty/template.config.toml`](diffhunk://#diff-629f76ebd26b9c8b4c3f5e6fbc0c169cbb4a …
=> [AURORA-575] templates: add descriptions

apps/framework-cli/src/cli/routines/scripts.rs, apps/framework-cli/src/framework/core/execute.rs, apps/framework-cli/src/framework/core/infra_reality_checker.rs, apps/framework-cli/src/framework/core/infrastructure_map.rs, apps/framework-cli/src/framework/core/partial_infrastructure_map.rs, apps/framework-cli/src/framework/scripts.rs, apps/framework-cli/src/framework/scripts/config.rs, apps/framework-cli/src/framework/scripts/executor.rs, apps/framework-docs/src/pages/moose/building/_meta.tsx, apps/framework-docs/src/pages/moose/building/workflows-2.mdx, packages/ts-moose-lib/src/dmv2/dataModelMetadata.ts, packages/ts-moose-lib/src/dmv2/index.ts, packages/ts-moose-lib/src/dmv2/internal.ts, packages/ts-moose-lib/src/index.ts, packages/ts-moose-lib/src/moose-runner.ts, packages/ts-moose-lib/src/scripts/activity.ts, packages/ts-moose-lib/src/scripts/runner.ts, packages/ts-moose-lib/src/scripts/workflow.ts
Example:
```
export interface Foo {
value: string;
}
export interface Bar {
value: string;
}
export interface Moo {
value: string;
}
export const task3 = new Task<Moo>("task3", {
run: async (input: Moo) => {
console.log(`task3 input: ${JSON.stringify(input)}`);
}
});
export const task2a = new Task<Bar, Moo>("task2a", {
run: async (input: Bar) => {
console.log(`task2a input: ${JSON.stringify(input)}`);
return {
value: `task2a processed: ${input.value}`,
};
},
onComplete: [task3],
});
export const task2b = new Task<Bar>("task2b", {
run: async (input: Bar) => {
console.log(`task2b input: ${JSON.stringify(input)}`);
}
});
export const task1 = new Task<Foo, Bar>("task1", {
run: async (input: Foo) => {
console.log(`task1 input: ${JSON.stringify(input)}`);
return {
value: `task1 processed: …
```
=> workflow dmv2 ts

templates/brainwaves/README.md
This pull request updates the `README.md` file for the Brainwaves Moose application to enhance the visual representation of the project.
Documentation update:
* [`templates/brainwaves/README.md`](diffhunk://#diff-87d3f301d8113c97edcac032c3db054a6727d78244f93f002dabcd01d80fdb13L5-R5): Replaced the static image with a GIF hosted on an external server to provide a more dynamic and engaging visual for the Brainwaves project.
=> Updated README.md for the Brainwaves Moose application 

apps/framework-cli/src/framework/python/wrappers/scripts/python_worker_wrapper/activity.py, apps/framework-cli/src/framework/python/wrappers/scripts/python_worker_wrapper/worker.py, apps/framework-cli/src/framework/python/wrappers/scripts/python_worker_wrapper/workflow.py, apps/framework-docs/src/pages/moose/building/workflows-2.mdx, packages/py-moose-lib/moose_lib/dmv2.py, packages/py-moose-lib/moose_lib/internal.py, packages/py-moose-lib/setup.py
Example:
```
class FooTask(BaseModel):
value: str
class BarTask(BaseModel):
value: str
def run_task3() -> None:
logger = Logger(action="run_task3")
logger.info(f"Ran run_task3")
task3 = Task[None, None](
name="task3",
config=TaskConfig(run=run_task3)
)
def run_task2a(input: BarTask) -> None:
logger = Logger(action="run_task2a")
logger.info(f"Ran run_task2a with input: {input.value}")
task2a = Task[BarTask, None](
name="task2a",
config=TaskConfig(run=run_task2a, on_complete=[task3])
)
def run_task2b(input: BarTask) -> None:
logger = Logger(action="run_task2b")
logger.info(f"Ran run_task2b with input: {input.value}")
task2b = Task[BarTask, None](
name="task2b",
config=TaskConfig(run=run_task2b)
)
def run_task1(input: FooTask) -> BarTask:
logger = Logger(action="run_task1")
logger.info(f"Ran …
```
=> workflow dmv2 python

packages/ts-moose-lib/package.json, packages/ts-moose-lib/src/connectors/apiSource.test.ts, packages/ts-moose-lib/src/connectors/apiSource.ts, packages/ts-moose-lib/src/connectors/dataSource.ts, packages/ts-moose-lib/src/index.ts, pnpm-lock.yaml
Example:
```
export interface PokemonResource {
name: string;
url: string;
}
export const PokemonPipeline = new IngestPipeline<PokemonResource>("Pokemon", {
table: true,
stream: true,
ingest: true,
});
interface PokemonList {
count: number;
next: string | null;
previous: string | null;
results: PokemonResource[];
}
const pokemonapi = new APISource<PokemonList, PokemonResource[]>({
name: "pokemonapi",
baseUrl: "https://pokeapi.co/api/v2",
endpoint: "/pokemon",
pagination: {
maxPages: 10,
delayBetweenRequests: 200,
getNextUrl: (response: PokemonList, headers: Headers) => {
return response.next;
},
},
extractItems: (response: PokemonList, headers: Headers) => {
return response.results;
},
});
const testConnectionResult = await pokemonapi.testConnection();
console.log("Test connection …
```
=> apisource ts

packages/ts-moose-lib/src/clients/redisClient.ts
Example:
```
const cache = await MooseCache.get();
const value = await cache.set("testSessionId", "true", 600);
if (value) {
console.log(`CACHE WAS SET BEFORE: ${value}`);
} else {
console.log ('CACHE SET FOR FIRST TIME. DOING WORK');
}
```
=> use get set

apps/framework-docs/src/components/badges.tsx, apps/framework-docs/src/styles/globals.css, apps/framework-docs/theme.config.jsx
- Fix badge colors to use proper light/dark mode variants (200/300 levels)
- Ensure buttons remain black in light mode
- Update footer to single column layout for better responsive design
- Fix script tag warnings by using next/script properly
Resolves light mode color inconsistencies and improves mobile UX
=> Fix light mode styling and footer layout

.github/workflows/release-cli.yaml
**fix: this file was cached it needs to be busted after updating**
=> mitchell/fix-index: json caching

packages/ts-moose-lib/src/dmv2/sdk/consumptionApi.ts
=> Revert "Revert "`call` method in ConsumptionApi in ts""

apps/framework-cli/src/infrastructure/olap/clickhouse/queries.rs
Not sure if this should be an enum instead of free-form strings.
=> add SummingMergeTree to ClickhouseEngine enum

apps/framework-cli/src/cli/local_webserver.rs
Enhanced by including server type, port, project name, and version in error messages. Update IntegrateChangesResponse struct to be public and derive Deserialize for improved usability.
=> Enhance error logging in local webserver 

apps/framework-cli/src/utilities/package_managers.rs
Included detailed context in UTF-8 decoding failures. This includes command, arguments, current directory, and raw output for better debugging.
=> Enhance error logging in package manager utilities

.github/workflows/test-framework-cli.yaml, packages/ts-moose-lib/src/browserCompatible.ts, packages/ts-moose-lib/src/dmv2/index.ts, packages/ts-moose-lib/src/dmv2/sdk/etl.test.ts, packages/ts-moose-lib/src/dmv2/sdk/etlPipeline.test.ts, packages/ts-moose-lib/src/dmv2/sdk/etlPipeline.ts, packages/ts-moose-lib/src/scripts/workflow.ts
Example:
```
const pokemonApi = new APISource<PokemonList, PokemonResource[]>({
name: "pokemonapi",
baseUrl: "https://pokeapi.co/api/v2",
endpoint: "/pokemon",
pagination: {
maxPages: 2, // 20 pokemons per page
delayBetweenRequests: 200,
getNextUrl: (context: APIContext<PokemonList>) => {
return context.response.next;
},
},
extractItems: (context: APIContext<PokemonList>) => {
return context.response.results;
},
});
export const etlPipeline = new ETLPipeline<PokemonResource, Pokemon>("testPipeline", {
extract: pokemonApi,
transform: async (sourceData: PokemonResource) => {
const transformedData = {
name: `transformed_${sourceData.name}`,
url: `transformed_${sourceData.url}`,
timestamp: new Date(),
};
console.log(`Transformed data: ${JSON.stringify(transformedData)}`);
return …
```
=> etlpipeline poc

templates/ads-b dlq/.gitignore, templates/ads-b dlq/.vscode/settings.json, templates/ads-b dlq/README.md, templates/ads-b dlq/app/datamodels/models.ts, templates/ads-b dlq/app/index.ts, templates/ads-b dlq/app/scripts/military_aircraft_tracking/1.fetch_and_ingest_military_aircraft.ts, templates/ads-b dlq/app/scripts/military_aircraft_tracking/config.toml, templates/ads-b dlq/aurora.config.toml, templates/ads-b dlq/moose.config.toml, templates/ads-b dlq/package.json, templates/ads-b dlq/template.config.toml, templates/ads-b dlq/tsconfig.json
This pull request introduces a new project template, "ADS-B DLQ," designed to process and transform aircraft tracking data into a standardized format while showcasing Moose's Dead Letter Queue (DLQ) capabilities. The changes include project configuration, data model definitions, ingestion pipeline setup, and supporting files for development and deployment.
=> add template: ADS-B / DLQ [PM-159]

.cursor/Dockerfile, .cursor/environment.json
Update Dockerfile to correctly configure the environment for the `ubuntu` user.
Resolves tool accessibility issues (Cargo, protoc, Docker, maturin) caused by user context and PATH mismatches.
=> Verify cursor environment setup

apps/framework-cli/src/cli/routines/openapi.rs
enum becomes `oneOf`, which the existing code could not handle
json schema from typia/pydantic should be trust worthy and not need extra validation
=> use fully dynamic json values when constructing the schmea

templates/ads-b-cf/template.config.toml
This pull request makes a minor update to the `templates/ads-b-cf/template.config.toml` file, enhancing the post-install instructions and modifying a configuration setting.
- **Post-install instructions update**:
- Added commands for running workflows (`militaryAircraftETL` and `laddAircraftETL`) to the `post_install_print` message.
- **Configuration adjustment**:
- Changed the `visible` setting from `true` to `false`.
=> add workflow run instructions

apps/framework-docs/src/components/badges.tsx, apps/framework-docs/src/components/bullet-points-card.tsx, apps/framework-docs/src/components/cta-card.tsx
- Update hero pill badges to use neutral colors
- Add borders to below icon containers to improve hover state
- Bullet point component prop fixes
=> Update docs UI styling

apps/framework-docs/src/components/ArgTable.tsx, apps/framework-docs/src/components/MuxVideo.tsx, apps/framework-docs/src/components/badges.tsx, apps/framework-docs/src/components/cta-card.tsx, apps/framework-docs/src/components/feature-cards.tsx, apps/framework-docs/src/components/staggered-card.tsx, apps/framework-docs/src/components/typography/index.tsx, apps/framework-docs/src/pages/moose/index.mdx, apps/framework-docs/src/styles/globals.css
- Fix inconsistent borders on mobile
- Fix inconsistent code block elements colors and borders  
- Fully expose install code block by wrapping
- Updated all cards to use consistent `rounded-xl` border radius
- Fixed code block styling with proper borders and radius
- Improved mobile typography sizing for card titles
- Added proper padding to Core Capabilities section
- Made badge styling consistent across components
- Fixed Nextra code block border radius and overflow
=> Moose UI Paper cuts

apps/framework-docs/src/pages/templates.mdx, apps/framework-docs/src/pages/templates/_meta.tsx, apps/framework-docs/src/pages/templates/brainmoose.mdx
- Introduced a new template for the Brainwave Analytics Platform, showcasing real-time EEG data processing and analytics.
- Updated the templates documentation to include the new Brainwave template with detailed features and setup instructions.
- Added Brainwave-related metadata to the existing templates list.
=> feat: add Brainwave Analytics Platform template and update documentation

apps/framework-cli/src/cli/routines/docker_packager.rs
https://stackoverflow.com/questions/68650325/how-to-pnpm-and-next-js-in-multi-stage-docker-file
=> Install PNPM in dockerfile

apps/framework-cli/src/cli/routines/docker_packager.rs, apps/framework-cli/src/framework/core/infra_reality_checker.rs, apps/framework-cli/src/framework/core/plan.rs, apps/framework-cli/src/project.rs, apps/framework-cli/src/utilities/constants.rs, apps/framework-cli/src/utilities/package_managers.rs, templates/ads-b/moose.config.toml, templates/typescript-empty/moose.config.toml, templates/typescript/moose.config.toml
**chore: allow pnpm and yarn for moose build**
=> mitchell/chore-allow: pnpm-and-yarn-in moose builds

apps/framework-cli/src/cli/routines/docker_packager.rs
=> mitchell/moose-build: monorepo support 2

apps/framework-docs/src/pages/moose/getting-started/quickstart.mdx
This pull request improves the clarity and usability of the Moose quickstart documentation by streamlining instructions, adding contextual explanations, and enhancing the structure of interactive content. The changes focus on making the setup process more user-friendly and easier to follow for new users.
**Documentation clarity and usability improvements:**
* Reworded the terminal restart instruction for clarity in the installation step.
* Simplified Docker verification instructions by merging the warning callout into the main text and clarifying the expected output and troubleshooting steps.
* Enhanced the explanation after running `moose dev` to direct users to the next step for more details.
* Improved command explanations by adding inline comments and merging previously separate …
=> Quickstart updates

apps/framework-cli/src/cli/local_webserver.rs, apps/framework-cli/src/infrastructure/orchestration/temporal.rs, apps/framework-cli/src/infrastructure/orchestration/temporal_client.rs
**fix: ready status for temporal in the cloud. made temporal region configurable**
=> mitchell/temporal-ready: for cloud

apps/framework-cli/src/cli/routines/code_generation.rs, apps/framework-cli/src/framework/python/generate.rs
WARNING I HAVE NOT TESTED THIS
=> fix path to external modules

apps/framework-cli/src/framework/python/scripts_worker.rs, apps/framework-cli/src/framework/typescript/scripts_worker.rs, apps/framework-cli/src/infrastructure/processes/orchestration_workers_registry.rs
Looks like we missed workflows when `RestartingProcess` was added couple months ago.
=> use restartingprocess for workflows like apis & functions
