.github/workflows/release-cli.yaml
apps/create-moose-app/package.json
apps/create-moose-app/scripts/release.sh
apps/create-moose-app/src/index.ts
apps/create-moose-app/tsconfig.json
apps/moose-cli-npm/README.md
apps/moose-cli-npm/package.json
apps/moose-cli-npm/package.json.tmpl
apps/moose-cli-npm/scripts/release-bin.sh
apps/moose-cli-npm/scripts/release-cli.sh
apps/moose-cli-npm/src/index.ts
apps/moose-cli-npm/tsconfig.json
pnpm-lock.yaml

* adds `moose` as a package name we claim for the CLI on npm
* adds `create-moose-app` as a package for the shortcut to init
* Updates workflows to automatically publish changes to moose alongside igloo for now

chore: claim moose namespaces

---

.github/workflows/release-cli.yaml
.github/workflows/test-igloo-cli.yaml

* Fixes the sentry error message that is looking at previous commits in the history
* updates the version of checkout github action

fix release

---

.github/workflows/release-cli.yaml

* Tries to fix the moose cli deployment (missing executable) by removing the gsap manual install from the release workflow
```
Run ./apps/moose-cli-npm/scripts/release-cli.sh 0.3.45
v0.3.45
Progress: resolved 1, reused 0, downloaded 0, added 0
.                                        |  WARN  Package name mismatch found while reading {"integrity":"sha512-pra7mFBNFK8YkfBr2KFIjK3xGr38K8SIfzH+Dvf0j+dAO70dqZX1s8xEqzK3Y4mlfB21Sa[6](https://github.com/514-labs/moose/actions/runs/7434887029/job/20229698113#step:9:7)i5o[7](https://github.com/514-labs/moose/actions/runs/7434887029/job/20229698113#step:9:8)bnC5rZSfarg==","tarball":"https://npm.greensock.com/@gsap/business/-/business-3.12.4.tgz"} from the store. This means that the lockfile is broken. Expected package: gsap@3.12.4. Actual package in …
```

remove manual gsap install from workflow

---

apps/framework-cli/src/cli/routines.rs
apps/framework-cli/src/cli/watcher.rs
apps/framework-cli/src/framework/controller.rs
apps/framework-cli/src/framework/schema.rs
apps/framework-cli/src/infrastructure/olap/clickhouse.rs
apps/framework-cli/src/infrastructure/olap/clickhouse/queries.rs
apps/framework-cli/src/project.rs

in preparation for the version sync trigger that writes to the data table

use explicit data table instead of inner table in materialized view

---

apps/framework-cli/Cargo.lock
apps/framework-cli/Cargo.toml

Removes 2 unused dependencies:
```
➜  framework-cli git:(nico/dependency-optimization) cargo machete
Analyzing dependencies of crates in this directory...
cargo-machete found the following unused dependencies in /Users/nicolasjoseph/code/514-labs/moose/apps/framework-cli:
moose-cli -- /Users/nicolasjoseph/code/514-labs/moose/apps/framework-cli/Cargo.toml:
bimap
dialoguer
openssl
If you believe cargo-machete has detected an unused dependency incorrectly,
you can add the dependency to the list of dependencies to ignore in the
`[package.metadata.cargo-machete]` section of the appropriate Cargo.toml.
For example:
[package.metadata.cargo-machete]
ignored = ["prost"]
You can also try running it with the `--with-metadata` flag for better accuracy,
though this may modify your Cargo.lock files. …
```

chore: remove unused dependencies

---

apps/framework-docs/src/pages/building/make-changes.mdx
apps/framework-docs/theme.config.jsx
apps/moose-cli-npm/README.md

There's a link in the docs taking users to https://github.com/shuding/nextra/src/pages/index.mdx. Looks like we can configure it with https://nextra.site/docs/docs-theme/theme-configuration#docs-repository.

Fix docs URL to not point to nextra repo

---

apps/framework-cli/src/cli/routines.rs
apps/framework-cli/src/project.rs

Because I had trouble getting the Rust Config crate to merge environment variables into the variables loaded from a config file, I fell back to doing this manually in an earlier PR.  This PR addresses the core issue that prevented me from succeeding on my earlier attempt.
The core issue was that I needed to use the Config `.prefix_separator("_")` in order to specify that environment variables will begin with MOOSE_ and that hierarchy would be represented with double underscore "dunderscore" as in the following example: `MOOSE_CLICKHOUSE__DB_NAME`
```rust
.add_source(Environment::with_prefix("MOOSE")
.prefix_separator("_")
.separator("__"),
```

Refactor code to pull environment variables using the Config crate

---

apps/framework-cli/src/infrastructure/stream/redpanda.rs

Cloud hosted instances of Redpanda require credentials.  This PR adds support for SASL credentials and choice of transport protocol.
```
export MOOSE_REDPANDA_CONFIG__SASL_USERNAME=fakename
export MOOSE_REDPANDA_CONFIG__SASL_PASSWORD=fakepassword
export MOOSE_REDPANDA_CONFIG__SASL_MECHANISM=SCRAM-SHA-512
export MOOSE_REDPANDA_CONFIG__SECURITY_PROTOCOL=SASL_SSL
```

Add security and protocol options to redpanda connections

---

apps/framework-cli/deploy/push.sh

This PR checks in the push.sh shell script which is a working prototype of a future `moose docker push` command for pushing local docker images to container repositories.
I delayed submitting this script because I had to test it against a previous deployment to ensure proper operation with Docker Hub.

Checking in push.sh shell script

---

apps/moose-console/src/app/ModelView.tsx
apps/moose-console/src/app/infrastructure/databases/[databaseName]/tables/[tableId]/table-tabs.tsx
apps/moose-console/src/app/primitives/models/[modelName]/page.tsx
apps/moose-console/src/lib/snippets.ts
apps/moose-console/src/lib/utils.ts

Changes the frontend to remove references to `MaterializedViews` this is a hotpatch but we should see how the reafactor of the UI will come along

fix: moose console removing Materialized Views

---

apps/framework-cli/deploy/senddata.sh

Shell script to use current date timestamp and random values when posting to a moose endpoint.
Script uses `/dev/urandom`,`tr `and `fold` and `head` commands to generate random eventID and userID
Requires the `curl` command to be installed.

Shell script for testing end points

---

apps/framework-cli/src/cli.rs
apps/framework-cli/src/cli/local_webserver.rs
apps/framework-cli/src/cli/logger.rs
apps/framework-cli/src/project.rs
apps/framework-cli/src/utilities/capture.rs
apps/framework-cli/src/utilities/constants.rs

Basic framework for capturing events. It's currently not sending the data anywhere. We can turn it on when there's a production moose app.
The capture macro is currently being called from top level CLI commands. We can add it to other places in the future. I also extracted out the session ID in the logger into a lazy static so other parts of the code can use the same session ID.

Rust based event capture sdk

---

apps/framework-cli/src/cli/routines/docker_packager.rs

The Dockerfile build was failing because it expects a versions folder to be present - even if empty.
```
COPY ./app ./app
COPY ./versions .moose/versions
```

Fix Dockerfile expects versions folder to be present

---

apps/framework-cli/src/cli/routines/initialize.rs
apps/framework-cli/src/framework/transform.ts

I tried [Deno.watchFs](https://examples.deno.land/watching-files), but it seemed unreliable with Docker volumes. Specifically, I would delete a flow file locally, see it deleted in the container, but Deno's filewatcher wasn't picking it up.
[Chokidar](https://www.npmjs.com/package/chokidar) was able to because of its polling feature:
> It is typically necessary to set this to true to successfully watch files over a network, and it may be necessary to successfully watch files in other non-standard situations.

Add filewatcher to flows for local dev

---

apps/framework-cli/deploy/senddata.sh

As I'm working on another data migration PR, I needed senddata to send multiple requests to make it easier to work with DCM data migrations.

added support for a counter to send n data requests

---

apps/framework-cli/src/utilities/docker.rs

This will help with automation for deploying. We can now do:
```
docker tag moose-df-deployment-x86_64-unknown-linux-gnu: latest moose-df-deployment-x86_64-unknown-linux-gnu:<versionChosenByTheUser>
```
for all builds, while before we had to dynamically get the version that was used to run the build to specify the tag.

improvement: change default docker image tag in the build script to be latest

---

apps/framework-cli/src/framework/transform.ts
apps/framework-cli/src/infrastructure/stream/redpanda.rs

https://docs.redpanda.com/current/reference/topic-properties/#retentionms
Flow service consumes message from topic & runs that message through a flow function. If the flow function finishes after `retention.ms` has elapsed, we try to mark the offset but the broker doesn't like it:
> {"level":"ERROR","timestamp":"2024-03-21T22:20:59.191Z","logger":"kafkajs","message":"[Connection] Response Fetch(key: 1, version: 11)","broker":"redpanda:9092","clientId":"deno-consumer","error":"The requested offset is not within the range of offsets maintained by the server","correlationId":6,"size":82}
Users' flow functions could have different exec times, so this allows them to configure the topic setting.

Add retention.ms as a config

---

apps/framework-cli/src/utilities/git.rs

I noticed through running the init on my system that it was defaulting to `master` instead of `main` the new standard.
This makes sure we don't mistakenly create with the old convention

chore: make sure the default git head is main

---

apps/framework-cli/src/cli/local_webserver.rs
apps/framework-cli/src/utilities/capture.rs
apps/framework-internal-app/app/datamodels/models.prisma
apps/framework-internal-app/project.toml

This creates a new model instead of using UserActivity so folks can continue to send test data to UserActivity without adding noise to instrumentation. There will be a follow-up PR to actually enable instrumentation after I verify the new model gets deployed.

Update instrumentation url & data model

---

apps/framework-cli/src/cli.rs

Prod flow initializes a moose project before running `moose prod`: https://github.com/514-labs/moose/blob/main/apps/framework-cli/src/cli/routines/docker_packager.rs#L51C1-L51C30.
But the `init` command no longer creates a .moose/models directory: https://github.com/514-labs/moose/blob/main/apps/framework-cli/src/cli/routines/initialize.rs#L18
So `moose prod` failed with error `called Result::unwrap() on an Err value: Models directory not found`

Setup models dir before starting prod server

---

apps/framework-internal-app/package.json

There was a CLI fix in https://github.com/514-labs/moose/releases/tag/v0.3.201 that's supposed to build the internal moose app as-is. But the latest deploy shows a data model is still missing. I think we need to bump the CLI version that internal moose app builds with.

Update internal moose to use latest cli

---

apps/framework-internal-app/package.json
pnpm-lock.yaml

Diff in `pnpm-lock.yaml` is from `pnpm install`. Also updated `apps/framework-internal-app/package.json` to use the latest CLI version because we removed an unused project config.

chore: bump cli version

---

.github/workflows/deploy-internal-app.yaml

`pnpm run build` is running `moose-cli build --docker`. We want to run that with telemetry disabled.

chore: disable telemetry from cicd

---

apps/framework-docs/src/pages/getting-started/new-project.mdx

fix quick start doc

---

apps/framework-cli/Cargo.lock
apps/framework-cli/Cargo.toml
apps/framework-cli/src/cli/watcher.rs
apps/framework-cli/src/framework/controller.rs
apps/framework-cli/src/framework/schema.rs
apps/framework-cli/tests/ts/extend.m.ts
apps/framework-cli/tests/ts/import.ts
apps/framework-cli/tests/ts/simple.ts
apps/moose-console/src/app/ModelView.tsx
apps/moose-console/src/app/infrastructure/databases/[databaseName]/tables/[tableId]/page.tsx
apps/moose-console/src/app/infrastructure/ingestion-points/[ingestionPointId]/page.tsx
apps/moose-console/src/app/primitives/models/[modelName]/page.tsx
apps/moose-console/src/components/ingestion-instructions.tsx
apps/moose-console/src/lib/snippets.ts

This is a copy-pasta from https://github.com/514-labs/moose/pull/549, minus doc changes & pr feedback changes. The goal is to get something merged to main in case we need to swarm on it.
I added an if-else to `parse_schema_file` so it can continue to work with current prisma schema. Next step is to iron out the wrinkles. Need to look into feedback from the original pr, and also what happens if we change `models.prisma` to `models.ts` with these interfaces.
```
interface UserActivity {
eventId: string;
timestamp: Date;
userId: string;
activity: string;
}
interface ParsedActivity {
eventId: string;
timestamp: Date;
userId: string;
activity: string;
}
```

wip: typescript instead of prisma

---

apps/framework-internal-app/package.json
pnpm-lock.yaml

bumps the version to be deployed

chore: update 514 internal app dependency

---

apps/framework-cli/src/framework/schema.rs
apps/framework-cli/tests/ts/extend.m.ts
apps/framework-cli/tests/ts/simple.ts

This allows us to run moose with typescript schema. The sdk is also generated. I tested with a schema like this:
```
type Key<T extends string | number> = T;
export interface UserActivity {
eventId: Key<string>;
timestamp: Date;
userId: string;
activity: string;
}
export interface ParsedActivity {
eventId: Key<string>;
timestamp: Date;
userId: string;
activity: string;
}
export enum MyEnum {
A, B, C
}
export interface MyTsModel {
id: Key<number>;
age: number;
flag: boolean;
abc: MyEnum;
opt?: string;
}
```
There are still some todos, like handling more enum cases brought up in the original PR. I believe those are tracked in https://linear.app/514/issue/514-624/support-enum-values. I also created a ticket for figuring out how we want the user to import Key …

Run moose dev with typescript schema

---

apps/framework-cli/src/cli/routines.rs
apps/framework-cli/src/cli/watcher.rs
apps/framework-cli/src/framework/typescript/generator.rs
apps/framework-cli/src/framework/typescript/templates.rs
apps/framework-cli/src/utilities/docker.rs

With deno, we can write
```ts
import { UserActivity as UserActivityOld } from "sdk/0.0/UserActivity.ts";
import { UserActivity as UserActivityNew } from "sdk/0.1/UserActivity.ts";
```
if we have `deno.json`
```json
{
"imports": {
"sdk/": "./.moose/test-flow-sdk/"
}
}
```
---
In another node project, I've tried `import {UserActivity as UserActivityOld } from 'test-flow-sdk/0.0/UserActivity'` with
```
"dependencies": {
"test-flow-sdk": "file:../test-flow/.moose/test-flow-sdk"
}
```
in `package.json`.

multiple versions SDK

---

apps/framework-cli/src/cli.rs
apps/framework-cli/src/cli/commands.rs
apps/framework-cli/src/cli/routines.rs
apps/framework-cli/src/cli/routines/logs.rs
apps/framework-cli/src/utilities/capture.rs
apps/framework-docs/src/pages/moose-cli.mdx

The default for `moose-cli logs` dumps the last few lines. Can add a `--filter <string>` or `--tail` or both. E.g:

moose logs command

---

apps/framework-cli/src/framework/typescript/templates.rs

A couple things from https://linear.app/514/issue/514-934/flows-quick-wins:
- Timestamp as string in default data model
- Change flow arg name from event to source so it's more generic
- Also updated imports to use models.ts

Update flow templates

---

README.md
apps/framework-cli/src/cli/local_webserver.rs

* Changes the relative image url for the logo to be the absolute path so that it doesn't break when using the readme in templates
* Fixes a typo when starting the dev server

fix typo and relative path changed to absolute path for templates

---

apps/framework-cli/src/project.rs

User could run moose dev, then we make a change to the deno scripts, and they try to run moose dev some time later. Currently, we only write those scripts to their .moose on first dev, so even though they have the latest moose-cli, they wouldn't automatically get the latest scripts.

Always write deno files on moose dev

---

apps/framework-cli/src/cli.rs
apps/framework-cli/src/cli/routines/dev.rs
apps/framework-cli/src/cli/routines/initialize.rs
apps/framework-cli/src/framework/languages.rs
apps/framework-cli/src/framework/typescript/generator.rs
apps/framework-cli/src/project.rs
apps/framework-cli/src/project/typescript_project.rs
apps/framework-cli/src/utilities/constants.rs
apps/framework-cli/src/utilities/docker.rs

* Do not panic when user directory is protected, properly fail
* Refactor the initialize routine to not use `Routines`
* Check project name for special characters to prevent a user from calling their project with a dot in there
* Removes `models` folder (not used)
* Adds some errors with the new error pattern

fix: properly error when there is a problem with initializing using the user home directory

---

apps/moose-console/src/components/query-interface.tsx

Part of Chris' demo flow is to land on the query interface, where we initially show where the query results appear:
&nbsp;
Then the demo clicks run to show that there's initially no data in there, so we want to show a different message:
&nbsp;

Show no results found msg

---

apps/framework-cli/src/cli/display.rs
apps/framework-cli/src/cli/logger.rs
apps/framework-cli/src/cli/routines.rs
apps/framework-cli/src/cli/routines/dev.rs
apps/framework-cli/src/cli/routines/docker_packager.rs
apps/framework-cli/src/cli/routines/stop.rs
apps/framework-cli/src/cli/watcher.rs
apps/framework-cli/src/framework/controller.rs

* Removes the spinners when running in prod mode
* Adds the ability to output logs as Json
* Send spinner logs to stdout and not stdErrr

chore: clean up logs for production

---

apps/framework-cli/src/cli.rs
apps/framework-cli/src/cli/local_webserver.rs
apps/framework-cli/src/cli/routines.rs
apps/framework-cli/src/cli/routines/migrate.rs
apps/framework-cli/src/cli/routines/version.rs
apps/framework-cli/src/cli/watcher.rs
apps/framework-cli/src/framework/controller.rs
apps/framework-cli/src/framework/data_model/schema.rs
apps/framework-cli/src/framework/prisma/parser.rs
apps/framework-cli/src/framework/typescript/parser.rs
apps/framework-cli/src/infrastructure/olap/clickhouse.rs
apps/framework-cli/src/infrastructure/olap/clickhouse/mapper.rs
apps/framework-cli/src/infrastructure/olap/clickhouse/model.rs
apps/framework-cli/src/infrastructure/olap/clickhouse/queries.rs
apps/framework-cli/src/infrastructure/olap/clickhouse/version_sync.rs
apps/framework-cli/src/infrastructure/olap/clickhouse_alt_client.rs
apps/framework-cli/src/project.rs

* Removes the global mutable project reference
* Do some refactors removing the Routines for the bump version and generate migration commands
* Removes the db_name from the Table object, it is a global project configuration
Currently in production, we can see some logs that should not be there since we are in prod mode. 
They are showing up because the production environment was only set on the global env and not on the local object
```rust
pub fn set_enviroment(&self, production: bool) {
let mut proj = PROJECT.lock().unwrap();
proj.is_production = production;
}
```
I removed the global. Through this, I am becoming more convinced that explicit dependency on the project object is necessary and will yield a return on the investment of punching through when necessary. It makes the dependency …

fix: fix project references for going to production

---

apps/framework-cli/src/framework/data_model.rs
apps/framework-cli/src/utilities/constants.rs
apps/framework-cli/src/utilities/git.rs
apps/framework-docs/src/pages/building/flows/setup.mdx

Updated flows docs so it doesn't mention .ts in the imports anymore. Also, I don't think we're using the `.generated.ts` stuff anymore? Let me know if I should revert those deletes.

Update flows docs

---

apps/moose-console/Dockerfile

Got the version from https://github.com/514-labs/moose/blob/main/pnpm-lock.yaml#L18457

Pin turbo version in console dockerfile

---

apps/framework-cli/Cargo.lock
apps/framework-cli/Cargo.toml
apps/framework-cli/src/cli.rs
apps/framework-cli/src/cli/local_webserver.rs
apps/framework-cli/src/cli/routines/flow.rs
apps/framework-cli/src/cli/routines/version.rs
apps/framework-cli/src/cli/watcher.rs
apps/framework-cli/src/framework/controller.rs
apps/framework-cli/src/framework/core.rs
apps/framework-cli/src/framework/core/code_loader.rs
apps/framework-cli/src/framework/core/primitive_map.rs
apps/framework-cli/src/framework/data_model/parser.rs
apps/framework-cli/src/framework/data_model/schema.rs
apps/framework-cli/src/framework/prisma/parser.rs
apps/framework-cli/src/framework/python/parser.rs
apps/framework-cli/src/framework/typescript/parser.rs
apps/framework-cli/src/project.rs
apps/framework-cli/src/utilities/git.rs

* renaming `schema_dir` to `data_model_dir` for consistency
* renaming `version()` to `cur_version` on the project for clarity 
* Add the `PrimitiveMap` object, it will be an object that will hold all the primitives as defined by the user. We will then transform that into the `InfrastructureMap` which will form a map of all the infra.
* Adds `file_path` and `version` to the `DataModel` to enable tracing it through changes and disambiguate through versions

chore: start plan feature with some ground work

---

.github/workflows/release-cli.yaml

Increase the size of the runners to make it go faster

chore: update github actions runner sizes

---

apps/framework-cli/src/cli/watcher.rs

....so we actually have the latest framework_object_versions to write to the state.

Write state after watcher parses data models

---

apps/framework-cli/src/cli/routines/docker_packager.rs
apps/framework-cli/src/cli/routines/version.rs
apps/framework-cli/src/project.rs
apps/framework-cli/src/utilities/constants.rs
apps/framework-cli/tests/cli_init.rs
apps/framework-docs/src/pages/building/dcm/concepts.mdx
apps/framework-docs/src/pages/building/dcm/walkthrough.mdx
apps/framework-docs/src/pages/getting-started/project-structure.mdx
apps/framework-docs/src/pages/moose-cli.mdx

* Renames `project.toml` to `moose.config.toml`
This is backward compatible so all current projects should continue working as is and we can remove the old code when that's not needed anymore

Nicolas/enable different `moose.config.toml` for moose project file

---

apps/framework-cli/Cargo.lock
apps/framework-cli/Cargo.toml
apps/framework-cli/src/cli.rs
apps/framework-cli/src/cli/commands.rs
apps/framework-cli/src/cli/routines.rs
apps/framework-cli/src/cli/routines/metrics_console.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/app.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/client.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/event.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/handler.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/lib.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/tui.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/ui.rs

Created a ratatui terminal ui that displays average latency and the total number of requests. It also has a table that shows the path of each endpoint that a request has been sent to and its average latency and the number of requests sent to that http endpoint. The user can view this console by running moose metrics in a separate terminal window

Metric console and moose metrics command

---

apps/framework-cli/src/cli/local_webserver.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/app.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/client.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/ui.rs

The metrics console now gets data once a second and calculates requests a second. Also I have removed the metrics endpoint from all calculations because it skews the numbers since the console is constantly making requests to it.
New UI Look:

Added requests per second metric to console and adjusted metrics calculations

---

apps/framework-cli/src/cli/local_webserver.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/app.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/client.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/handler.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/tui.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/ui.rs

Each http endpoint now has a detailed view which the user can access by navigating to the endpoint they want on the table and then clicking enter. In the detailed view there is metrics specific to that endpoint and a bar chart showing the number of requests under X latency in ms. There is also a sparkline graph chart that shows the number of requests per second over the past ___ seconds. The user can view a longer timeframe by expanding the console window horizontally. In the main view all endpoints currently receiving requests are colored purple, ingest and consumption endpoints colored green (not getting requests), and other endpoints colored cyan (not getting requests).
Detailed view UI:
In iterm code terminal:
In normal mac terminal:
Example of highlighted endpoints

Detailed metrics views for each http endpoint

---

apps/framework-cli/src/cli/local_webserver.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/app.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/client.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/ui.rs
apps/framework-cli/src/metrics.rs

Instruments moose using prometheus counter to track bytes in and out per sec. Bytes in and out per sec is displayed in metrics console. There is bytes in/out per sec displayed for the whole app and for each path in the detailed view.
Screenshots:

Bytes in and out metric tracking

---

apps/framework-docs/src/pages/building/streaming-functions/setup.mdx

Changed command "functions" to "function"

Fixed docs typo in streaming functions page.

---

apps/framework-cli/src/cli/local_webserver.rs
apps/framework-cli/src/cli/routines.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/app.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/client.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/handler.rs
apps/framework-cli/src/cli/routines/metrics_console/run_console/ui.rs
apps/framework-cli/src/cli/watcher.rs
apps/framework-cli/src/framework/core/execute.rs
apps/framework-cli/src/infrastructure/processes.rs
apps/framework-cli/src/infrastructure/processes/kafka_clickhouse_sync.rs
apps/framework-cli/src/infrastructure/stream/redpanda.rs
apps/framework-cli/src/metrics.rs

Instruments moose to track the number of messages sent to kafka from each ingest point and the number of messages received from kafka for each data model. Lag and messages per second are also calculated and displayed to the user. The user can also toggle between tables and then use the arrow keys to scroll within the table they have selected
Screen Shot:

Kafka instrumentation and displaying metrics

---

apps/framework-docs/src/pages/_meta.json
apps/framework-docs/src/pages/metrics-console.mdx

Added a new page in the docs to give a more detailed explanation of what metrics moose tracks and where they come from.

Metrics console docs update

---

apps/framework-cli/src/cli.rs
apps/framework-cli/src/cli/settings.rs

Tested by turning the flag on - it works.
This activates it as a default

chore: default metrics instrumentation

---

apps/framework-cli/src/infrastructure/olap/clickhouse.rs
apps/framework-cli/src/infrastructure/olap/clickhouse/client.rs
apps/framework-cli/src/infrastructure/olap/clickhouse/queries.rs
apps/framework-cli/src/infrastructure/olap/clickhouse/version_sync.rs
apps/framework-cli/src/infrastructure/olap/clickhouse_alt_client.rs

Wraps all in double quotes to enable names with dashes for branches

fix: enable wrap all clickhouse db and table names in queries with double quotes

---

apps/framework-cli/src/cli.rs

The launch of the `moose dev` command performs schema validation via initialize_project_state()
However, the `moose build` command does not perform the same valuation.
Lines 262 call the initialize_project_state() before building the docker image.

Patch to allow schema validation before completing build process

---

apps/framework-cli/src/cli/routines/docker_packager.rs

* Changes user pattern to not run as root user
* Use base node image instead of making our own
* Change order of instructions to maximize caching
Build is now 30s

chore: harden docker images

---

apps/framework-cli/src/utilities/docker-compose.yml

Cleans up docker compose options for redpanda

chore: replace flags with pre-built redpanda dev flag

---

apps/framework-cli/src/cli.rs

Small fix for when generating the SDK, the check needs to be where we write the files, not where we read from

fix: check that the writing destination is empty not the project

---

.github/workflows/release-cli.yaml
apps/create-moose-app/scripts/release.sh

Looks like we broke main release on Friday by adding some dependencies.
Ref: https://github.com/514-labs/moose/actions/runs/10746946493/job/29808833294

chore: fix main release build by adding install step to the publish script

---

apps/framework-cli/src/framework/typescript/parser.rs
apps/framework-cli/src/framework/typescript/ts_node.rs

This was breaking the deployment in boreal since the notice is on the `stderr` channel

fix: deactivate the update notifier from npm

---

apps/framework-cli/src/utilities/validate_passthrough.rs

without calling `next_value` it expects a new key in JSON when the next tokens are `:` and the value

fix handling after unknown field

---

apps/framework-cli/src/framework/python/consumption.rs
apps/framework-cli/src/framework/python/scripts/consumption_runner.py
apps/framework-cli/src/infrastructure/processes/consumption_registry.rs
packages/py-moose-lib/moose_lib/main.py
packages/py-moose-lib/setup.py
packages/ts-moose-lib/package.json

Example:
```
from moose_lib import cli_log, CliLogData, ConsumptionApiResult, JWTPayload, MooseClient, ConsumptionApiResult
from typing import Optional, Any
def run(client: MooseClient, params: Any, jwt: Optional[JWTPayload]):
cli_log(CliLogData(action="UserActivity", message=f"JWT payload: {jwt}", message_type="Info"))    
limit = int(params.get('limit', [10])[0])
query_result = client.query(
'''SELECT *
FROM UserActivity_0_0
LIMIT {limit}''',
{
"limit": limit
}
)
return ConsumptionApiResult(status=200, body=query_result)
```

Support jwt in python consumption api

---

apps/framework-cli/src/cli/routines.rs
apps/framework-cli/src/infrastructure/processes/cron_registry.rs
packages/ts-moose-lib/src/moose-exec.ts

Fixes:
* Fix for moose-exec and moose cron path setup for typescript execution
* Fix for moose cron duplicate cron registration during startup
* Defensive programming in cron_registry.rs to avoid duplicate jobs.

Moose cron fixes

---

apps/framework-cli/src/cli/routines.rs
apps/framework-cli/src/framework/core/execute.rs

This PR explores using the Redis-based leadership lock to ensure that only one moose instance in a multi-moose cluster can execute an initial migration. The `execute_initial_infra_change` seems like a good place to explore this approach.
However, it seems that the entire concept of how "plans" are handled needs to be considered in the multi-moose scenario. So, in this regard, this initial PR is arguably incomplete. I wanted to float this by you guys to get your take on the general approach/direction.

Multi-moose data migration increment

---

apps/framework-cli/src/infrastructure/redis/redis_client.rs

Docker containers include a HOSTNAME environment variable that contains the short ID of the docker container.  This PR introduces a one-line change:
```rust
let instance_id = std::env::var("HOSTNAME").unwrap_or_else(|_| Uuid::new_v4().to_string());
```
which will use the HOSTNAME if present; else, default to a UUID.
The reason for using this approach rather than our existing config crate and moose.config.toml is because we expect moose environment variables to be prefixed with `MOOSE_` and the docker HOSTNAME environment variable, if present, will not have that prefix.
The usefulness of this approach is that we'll be able to tie moose usage of Redis keys to exact containers.

Attempt to use the docker container ID

---

apps/framework-cli/src/infrastructure/redis/redis_client.rs

This PR fixes a bug that is causing the service_name to be duplicated in the Redis resource lock key.

Bug fix for duplicate service_name entries

---

apps/framework-cli/src/cli/local_webserver.rs
apps/framework-cli/src/project.rs

Would allow the user to build jwt support piecemeal (i.e. handle consumption first, then ingest)

add jwt ingest flag

---

apps/framework-cli/src/cli/display.rs
apps/framework-cli/src/cli/watcher.rs
apps/framework-cli/src/framework/core/infrastructure/table.rs
apps/framework-cli/src/framework/core/infrastructure_map.rs
apps/framework-cli/src/framework/data_model/config.rs
apps/framework-cli/src/framework/data_model/model.rs
apps/framework-cli/src/framework/python.rs
apps/framework-cli/src/framework/python/datamodel_config.rs
apps/framework-cli/src/infrastructure/olap/clickhouse.rs
apps/framework-cli/src/infrastructure/olap/clickhouse/errors.rs
apps/framework-cli/src/infrastructure/olap/clickhouse/queries.rs
packages/py-moose-lib/moose_lib/main.py
packages/ts-moose-lib/src/index.ts

* Adds the 'deduplicate' field in the data model storage configuration
* Handle errors during watch to not crash
* Move Python data config loading to the python module
* Added some create table tests

feat: add the ability to leverage clickhouse deduplicating merge tree to remove duplicates

---

apps/framework-cli/src/utilities/docker.rs

`docker pull docker.io/clickhouse/clickhouse-server:latest` to force an update

stop overriding clickhouse version

---

apps/framework-cli/src/cli/routines.rs
apps/framework-cli/src/cli/watcher.rs
apps/framework-cli/src/infrastructure/olap/clickhouse/inserter.rs
apps/framework-cli/src/infrastructure/processes/kafka_clickhouse_sync.rs
apps/framework-cli/src/infrastructure/redis/redis_client.rs

next is somehow to make leader know all followers have stopped syncing and migration is now safe to perform
---
`iterate_subscriber` was a premature abstraction. `select` has to be used to jump out of the `recv` call in one but not the other.

global variable to pause kafka clickhouse sync

---

apps/framework-cli/src/infrastructure/olap/clickhouse.rs
apps/framework-cli/src/infrastructure/olap/clickhouse/mapper.rs
apps/framework-cli/src/infrastructure/olap/clickhouse/model.rs
apps/framework-cli/src/infrastructure/olap/clickhouse/queries.rs

For some reason I did not put in the implementation for creating a table with ReplacingMergeTree from the get go.
This fixes that issue

fix: enable replacing merge tree to be setup on a brand new table

---

.github/workflows/release-cli.yaml
scripts/wait-for-npm-package.sh

I noticed builds on main were failing because a dependency was not available yet on npm.
this should make the release process more resilient

chore: add scripts to make sure packages are published and available before moving to the next step

---

apps/framework-cli/src/cli/routines.rs

- Extend leadership lock interval
- If same instance of moose was the leader and lost leaderhip then if it renewal leadership it should not register cron jobs.

Update leadership lock handling

---

apps/framework-cli/src/cli.rs

This pull request includes a small change to the `apps/framework-cli/src/cli.rs` file. The change adds a log statement to display the Moose version when the `prod` command is executed.
* [`apps/framework-cli/src/cli.rs`](diffhunk://#diff-395b4c1e79d334e05ed21f84d9ee188d69b5f680d11a84e64cd85a4d739e811dR554-R555): Added a log statement to display the Moose version in the `top_command_handler` function when the `prod` command is executed.

feat: add version logging statement when moose prod starts

---

.github/workflows/release-cli.yaml

Trying to see if that fixes the publishing of the python wheel

fix: remove stop gap for compilation

---

.github/workflows/release-cli.yaml
apps/framework-cli/pyproject.toml

This pull request includes updates to the `.github/workflows/release-cli.yaml` file to improve the build and release process for the CLI application. The most important changes are related to the configuration of the build target and the naming of the release job.
Improvements to build configuration:
* Added a conditional configuration for `manylinux` targeting `aarch64-unknown-linux-gnu` to address an issue with the `ring` crate. (`.github/workflows/release-cli.yaml`, [.github/workflows/release-cli.yamlR228-R229](diffhunk://#diff-499c73a2f13eb6f53b0606fab451145e22009c29aac1e2834c960009e4641dc1R228-R229))
Improvements to job naming:
* Renamed the `release-python` job to `Release Python Wheels` for better clarity. (`.github/workflows/release-cli.yaml`, …

fix: attempt release fix 2

---

Cargo.lock
apps/framework-cli/Cargo.toml
apps/framework-cli/src/cli/local_webserver.rs
apps/framework-cli/src/cli/routines.rs
apps/framework-cli/src/cli/routines/openapi.rs
apps/framework-cli/src/cli/watcher.rs
apps/framework-cli/src/framework/consumption/model.rs
apps/framework-cli/src/framework/core/infrastructure/api_endpoint.rs
apps/framework-cli/src/framework/core/infrastructure_map.rs
apps/framework-cli/src/utilities/constants.rs
packages/protobuf/infrastructure_map.proto
pnpm-lock.yaml

What's new since https://github.com/514-labs/moose/pull/1993:
- Updated moose proto to include consumption query params
- Updated openapi to just use the infra map that's already in memory rather than re-querying
- Tested with released moose-cli to create the infra map as-is, then restarted moose with this change to verify we can deserialize older infra map

openapi + egress in redis inframap

---

apps/framework-cli/Cargo.lock
apps/framework-cli/Cargo.toml
apps/framework-cli/src/cli.rs
apps/framework-cli/src/cli/commands.rs
apps/framework-cli/src/cli/routines/scripts.rs
apps/framework-cli/src/framework/python/executor.rs
apps/framework-cli/src/framework/scripts.rs
apps/framework-cli/src/framework/scripts/executor.rs
apps/framework-cli/src/infrastructure/orchestration/temporal.rs

This pull request introduces several changes to the `framework-cli` application, primarily focusing on integrating Temporal workflows and enhancing the command-line interface to manage these workflows. The most important changes include adding new dependencies, updating the command-line interface to support new workflow commands, and implementing functions to interact with Temporal.
* Added `temporal-sdk-core-protos` as a new dependency in `Cargo.toml` to support Temporal workflows.
* Implemented `connect_to_temporal` and `get_temporal_client` functions to establish a connection with the Temporal server. [[1]](diffhunk://#diff-395b4c1e79d334e05ed21f84d9ee188d69b5f680d11a84e64cd85a4d739e811dR1076-R1082) [[2]](diffhunk://#diff-e7d45c2819ca30b9052f5d58593637965e781f7d493a586f7c3ad89c873ae0bbR …

handling of list and terminate

---

apps/framework-cli/src/cli.rs
apps/framework-cli/src/cli/commands.rs
apps/framework-cli/src/cli/routines/scripts.rs

This pull request introduces a new feature to the `framework-cli` application: the ability to get the status of a workflow. The changes include updates to the command handling, new functionality in the workflow routines, and necessary imports.
New feature implementation:
* [`apps/framework-cli/src/cli.rs`](diffhunk://#diff-395b4c1e79d334e05ed21f84d9ee188d69b5f680d11a84e64cd85a4d739e811dL31-R34): Added a new command `Status` to the workflow commands and included the `get_workflow_status` function in the command handler. [[1]](diffhunk://#diff-395b4c1e79d334e05ed21f84d9ee188d69b5f680d11a84e64cd85a4d739e811dL31-R34) [[2]](diffhunk://#diff-395b4c1e79d334e05ed21f84d9ee188d69b5f680d11a84e64cd85a4d739e811dR1024-R1026)
* [`apps/framework-cli/src/cli/commands.rs`](diffhunk://#diff-e7f0aaaa20bae4136 …

workflow status command

---

Cargo.lock
apps/framework-cli/Cargo.toml
apps/framework-cli/src/framework/python/executor.rs
apps/framework-cli/src/framework/python/wrappers/consumption_runner.py
apps/framework-cli/src/framework/scripts.rs
apps/framework-cli/src/framework/scripts/collector.rs
apps/framework-cli/src/framework/scripts/config.rs
apps/framework-cli/src/framework/scripts/executor.rs
apps/framework-cli/src/infrastructure/processes/orchestration_workers_registry.rs
apps/framework-cli/src/utilities/constants.rs

For example, a config like this:
```
name = 'testretry'
schedule = ''
retries = 3
timeout = '1m'
steps = ['step1']
```
would give each workflow 1 minute for each of the 3 retries.

add retry & timeout in workflow run cmd

---

apps/framework-cli/src/utilities/docker-compose.yml.hbs

Before (~22s on my machine):
https://github.com/user-attachments/assets/0c807ab6-876f-4430-931a-be48558dbe7d
After (< 1s)
https://github.com/user-attachments/assets/b574dd10-04fc-41d0-b8a8-00bc59bc8b27

speed up temporal health check

---

packages/ts-moose-lib/src/scripts/activity.ts
packages/ts-moose-lib/src/scripts/workflow.ts

For example, this configures it to one retry. If the config is omitted, retries default to 3, like in python workflow.
```
export default function createTask(input?: object) {
return {
task: step1,
config: {
retries: 1,
}
} as TaskDefinition;
}
```

task retry ts workflow

---

apps/framework-cli/src/framework/python/wrappers/scripts/python_worker_wrapper/activity.py

For example, you can do `moose-cli workflow run wfname` and just define the task function without arguments
```
@task
def task1():
return {
"task": "task1",
"data": {
"hello": "world"
}
}
@task
def task2(input: dict):
task2.logger.info(f"task2 input: {input.get("hello")}")
return {
"task": "task2",
"data": None
}
```

optional py workflow input data

---

apps/framework-cli/src/utilities/git.rs

This pull request includes a small change to the `apps/framework-cli/src/utilities/git.rs` file. The change adds `.ts-node` to the list of entries in `.gitignore` for TypeScript projects.
* [`apps/framework-cli/src/utilities/git.rs`](diffhunk://#diff-c2aecb1c159262c18354cc82a74d3f1c51e6afb186804fc1c7da3c774b0194c3L45-R45): Added `.ts-node` to the `.gitignore` entries for TypeScript projects.

ignore .ts-node

---

apps/framework-cli/src/cli.rs
apps/framework-cli/src/cli/commands.rs
apps/framework-cli/src/cli/local_webserver.rs
apps/framework-cli/src/cli/routines.rs
apps/framework-cli/src/cli/routines/build.rs
apps/framework-cli/src/cli/routines/docker_packager.rs

This pull request introduces a new function for building deployment packages without using Docker and updates the CLI to support this new functionality. Additionally, it makes several changes to improve the flexibility and error handling of the web server.
* [`apps/framework-cli/src/cli/routines/build.rs`](diffhunk://#diff-3f227ace3a120ff6317ae024e98c9c3a16040549a735fc0c2a7a210b834ef85aR1-R291): Added the `build_package` function to create deployment packages without Docker. This includes handling various file operations, copying dependencies, running checks, and creating an archive.
* [`apps/framework-cli/src/cli.rs`](diffhunk://#diff-395b4c1e79d334e05ed21f84d9ee188d69b5f680d11a84e64cd85a4d739e811dL20-R26): Updated the `use` statements to include `with_spinner` and added a call to …

Moose build without docker

---

apps/framework-cli/src/cli/routines.rs
apps/framework-cli/src/infrastructure/olap/clickhouse/inserter.rs
apps/framework-cli/src/infrastructure/processes/kafka_clickhouse_sync.rs

This pull request focuses on removing the pause/resume functionality for writing to ClickHouse from Kafka. The changes span across multiple files, simplifying the codebase and removing unnecessary synchronization mechanisms.
Key changes include:
* [`apps/framework-cli/src/cli/routines.rs`](diffhunk://#diff-98a40f984655c2a7cb4ffee8fe2e9e14420b623ffbb1257bd355621f0537d17fL281-R282): Removed the `clickhouse_writing_pause_button` function calls and related log messages in the `process_pubsub_message` function.
* [`apps/framework-cli/src/infrastructure/olap/clickhouse/inserter.rs`](diffhunk://#diff-15f02b314e130778bd56d81e964452d161d74a8dcf48bb70f8e795b936e4daa2L130-L136): Removed the `pause_receiver` and related logic from the `Inserter` implementation.
* …

fix: remove migration stop from syncing

---

apps/framework-cli/src/infrastructure/olap/clickhouse/inserter.rs
apps/framework-cli/src/infrastructure/processes/kafka_clickhouse_sync.rs

This pull request includes several changes aimed at simplifying the `Inserter` implementation and improving the testability and performance of the `ClickHouse` inserter. The most important changes include the removal of unnecessary `Arc` and `Mutex` usage, the addition of new type aliases for better code readability, and the introduction of a manual flush mechanism in tests.
* Removed `Arc` and `Mutex` from `BatchQueue` and `client` in `Inserter`, simplifying the code and reducing overhead. (`apps/framework-cli/src/infrastructure/olap/clickhouse/inserter.rs`)
* Added new type aliases `PartitionOffsets` and `PartitionSizes` to improve code readability. (`apps/framework-cli/src/infrastructure/olap/clickhouse/inserter.rs`)
* Modified tests to use a mutable `Inserter` and removed unnecessary …

chore: simplify syncing code while adding backpressure

---

apps/framework-cli/src/framework/core/infrastructure_map.rs
apps/framework-cli/src/infrastructure/stream/redpanda.rs
packages/ts-moose-lib/src/streaming-functions/runner.ts

The reduced duration is per retry (of exponential retries).
Increased count so that the total retry duration stays approximately the same.

reduce ts streaming max retry time

---

apps/framework-cli/src/cli/local_webserver.rs
apps/framework-cli/src/cli/routines/ls.rs
apps/framework-cli/src/cli/routines/peek.rs
apps/framework-cli/src/cli/routines/ps.rs
apps/framework-cli/src/framework/core/code_loader.rs
apps/framework-cli/src/framework/core/execute.rs
apps/framework-cli/src/framework/core/infra_reality_checker.rs
apps/framework-cli/src/infrastructure/processes/functions_registry.rs
apps/framework-cli/src/infrastructure/stream.rs
apps/framework-cli/src/infrastructure/stream/kafka/client.rs
apps/framework-cli/src/project.rs

This pull request includes changes to the `apps/framework-cli/src/project.rs` file to correct the alias for the `KafkaConfig` field in the `Project` struct. The most important change involves renaming the alias to ensure the correct configuration is used.
* [`apps/framework-cli/src/project.rs`](diffhunk://#diff-74c0d9db35c20148e80233c14d50f29beafdbf7093a1e1626fb5d1aedb67e012L156-R157): Changed the alias for the `KafkaConfig` field from `redpanda_config` to `kafka_config` to correct the configuration mapping.

fix: revert default config

---

apps/framework-cli/src/cli/local_webserver.rs
apps/framework-cli/src/cli/routines.rs
apps/framework-cli/src/cli/routines/ls.rs
apps/framework-cli/src/cli/routines/peek.rs
apps/framework-cli/src/cli/watcher.rs
apps/framework-cli/src/framework/core/execute.rs
apps/framework-cli/src/framework/core/plan.rs
apps/framework-cli/src/infrastructure/redis/leadership.rs
apps/framework-cli/src/infrastructure/redis/redis_client.rs
apps/framework-cli/src/metrics.rs
apps/framework-cli/src/metrics_inserter.rs

This pull request includes significant changes to the `apps/framework-cli/src/cli/local_webserver.rs` and `apps/framework-cli/src/cli/routines.rs` files to simplify the handling of the `RedisClient` by removing the `Mutex` wrapper. The most important changes include modifying the function signatures and logic to directly use `Arc<RedisClient>` instead of `Arc<Mutex<RedisClient>>`.
* Removed the `Mutex` wrapper from `redis_client` in the `RouteService` struct and various function signatures, simplifying the code. [[1]](diffhunk://#diff-fee871a911a583459e462af9d8c682e0f98be4006d2866ce74821b05ee304a9aL270-R271) [[2]](diffhunk://#diff-fee871a911a583459e462af9d8c682e0f98be4006d2866ce74821b05ee304a9aL353-R353) [[3]](diffhunk://#diff-fee871a911a583459e462af9d8c682e0f98be4006d2866ce74821b05ee304a9 …

fix: escape on ctrl+c and a lot of mutexes

---

apps/framework-docs/src/pages/_meta.ts
apps/framework-docs/src/pages/planning.mdx

This pull request includes new documentation for the Infrastructure Planning feature in Moose and updates the metadata file to include this new section. The most important changes are the addition of the `planning.mdx` file and the update to the `_meta.ts` file to reference the new section.
Documentation updates:
* [`apps/framework-docs/src/pages/planning.mdx`](diffhunk://#diff-a30117585f8b050d879965c2363ed9e97629205f60e58b71c770baaea2a4845eR1-R132): Added comprehensive documentation for the Infrastructure Planning feature, including an overview, usage instructions, workflow descriptions, best practices, and troubleshooting tips.
Metadata updates:
* [`apps/framework-docs/src/pages/_meta.ts`](diffhunk://#diff-bba55741660583accd5270ca0dbb0cd70d66205dad611a775a3cde279749eb4dR25): Added a new …

docs: add some planning docs

---

apps/framework-cli/src/cli.rs
apps/framework-cli/src/cli/routines/build.rs

This pull request includes several changes to enhance logging and error handling in the `apps/framework-cli` project. The most important changes are focused on improving the `top_command_handler` function and the `run_moose_check` function.
Enhancements to logging and error handling:
* [`apps/framework-cli/src/cli.rs`](diffhunk://#diff-395b4c1e79d334e05ed21f84d9ee188d69b5f680d11a84e64cd85a4d739e811dL248-R251): Updated the `info!` log message in the `Commands::Check` block to include the value of `write_infra_map`.
* [`apps/framework-cli/src/cli.rs`](diffhunk://#diff-395b4c1e79d334e05ed21f84d9ee188d69b5f680d11a84e64cd85a4d739e811dR265-R286): Added detailed error handling and logging when loading the `InfrastructureMap` based on the `write_infra_map` flag.
* …

fix: moose check dmv2

---

apps/framework-cli/src/framework/core/infrastructure_map.rs
apps/framework-cli/src/infrastructure/olap/clickhouse/mapper.rs
apps/framework-cli/src/infrastructure/olap/clickhouse/queries.rs

`stdout.read_to_string` hangs when output is large
`engine: ClickHouseEngines.AggregatingMergeTree` is ignored

fixes for DMv2

---

packages/py-moose-lib/moose_lib/__init__.py
packages/py-moose-lib/moose_lib/data_models.py
packages/py-moose-lib/moose_lib/dmv2-serializer.py
packages/py-moose-lib/moose_lib/dmv2.py
packages/py-moose-lib/moose_lib/internal.py
packages/py-moose-lib/moose_lib/main.py

no need to write `moose_lib.dmv2`
Renamed `DataModelConfigV2` to `IngestPipelineConfig`.
misc cleanups

MOOSE-1411: clean up for dmv2 in python

---

.github/workflows/release-cli.yaml

This pull request includes changes to the `.github/workflows/release-cli.yaml` file to improve the handling of the `pypi-cleanup` command by adding conditional checks for different outputs. The most important change is the addition of conditional handling for the "No releases were found" message.
Improvements to workflow:
* [`.github/workflows/release-cli.yaml`](diffhunk://#diff-499c73a2f13eb6f53b0606fab451145e22009c29aac1e2834c960009e4641dc1L585-R608): Added conditional handling for the "No releases were found" message in the `pypi-cleanup` command to ensure the script continues running even when no releases are found.

fix: clean up script for releases

---

apps/framework-cli/src/cli.rs
apps/framework-cli/src/cli/commands.rs
apps/framework-cli/src/cli/display.rs
apps/framework-cli/src/cli/routines/ls.rs
apps/framework-cli/src/framework/data_model/config.rs

```
View Moose primitives & infrastructure
Usage: moose-cli ls [OPTIONS]
Options:
--type <TYPE>  Filter by infrastructure type (tables, streams, ingestion, sql_resource, consumption)
--name <NAME>  Filter by name (supports partial matching)
--json         Output results in JSON format
-h, --help         Print help
```

moose ls for dmv2

---

apps/framework-cli-e2e/test/templates.test.ts
packages/ts-moose-lib/src/streaming-functions/runner.ts

This pull request includes several changes to the `apps/framework-cli-e2e/test/templates.test.ts` and `packages/ts-moose-lib/src/streaming-functions/runner.ts` files. The main updates involve adding a new utility function for verifying consumer logs and modifying the key generation for streaming functions.
* [`apps/framework-cli-e2e/test/templates.test.ts`](diffhunk://#diff-bf6accc02eed3b986feb4d9795a15846a17c84ae10049e00a3ad82074ae426dbR185-R208): Added a new `verifyConsumerLogs` function to the `utils` object. This function reads the consumer logs and checks for expected output strings.
* [`apps/framework-cli-e2e/test/templates.test.ts`](diffhunk://#diff-bf6accc02eed3b986feb4d9795a15846a17c84ae10049e00a3ad82074ae426dbR315-R321): Updated test cases to use the new `verifyConsumerLogs` …

chore: add integration test for consumer function

---

.github/workflows/test-framework-cli.yaml

This pull request includes a small change to the `.github/workflows/test-framework-cli.yaml` file. The change adds `Cargo.lock` and `pnpm-lock.yaml` to the list of patterns in the `jobs:` section.
* [`.github/workflows/test-framework-cli.yaml`](diffhunk://#diff-3b823426133c426c409ab0bec8905fb58185ad27ffa6c316b5e2fc9c7d86ef16R45-R46): Added `Cargo.lock` and `pnpm-lock.yaml` to the list of patterns.

add pnpm lock and cargo lock files to triggering event for tests

---

Cargo.lock

Bumps the cargo group with 1 update in the / directory: [crossbeam-channel](https://github.com/crossbeam-rs/crossbeam).
Updates `crossbeam-channel` from 0.5.14 to 0.5.15
- [Release notes](https://github.com/crossbeam-rs/crossbeam/releases)
- [Changelog](https://github.com/crossbeam-rs/crossbeam/blob/master/CHANGELOG.md)
- [Commits](https://github.com/crossbeam-rs/crossbeam/compare/crossbeam-channel-0.5.14...crossbeam-channel-0.5.15)
---
updated-dependencies:
- dependency-name: crossbeam-channel dependency-version: 0.5.15 dependency-type: indirect dependency-group: cargo ...

chore(deps): bump crossbeam-channel

---

.github/workflows/test-framework-cli.yaml
apps/framework-cli-e2e/test/templates.test.ts
apps/framework-cli/src/framework/core/partial_infrastructure_map.rs
apps/framework-cli/src/framework/core/plan.rs

This pull request updates the GitHub Actions workflow for the Test Framework CLI to include pull request events as triggers. The most important change is enabling the workflow to run on pull request events such as `opened`, `synchronize`, and `reopened`.
Trigger updates in `.github/workflows/test-framework-cli.yaml`:
* Added `pull_request` event with types `opened`, `synchronize`, and `reopened` to the workflow triggers. This ensures the workflow is executed when pull requests are created, updated, or reopened.

chore: enable public forks to trigger the testing workflow

---

.github/workflows/test-framework-cli.yaml

This pull request updates the GitHub Actions workflow configuration in `.github/workflows/test-framework-cli.yaml` to improve compatibility with pull request events and ensure the correct repository and commit are checked out during workflow runs. The most significant changes include removing the `push` trigger for non-main branches, updating the `actions/checkout` step to use the pull request's repository and commit, and upgrading the `actions/checkout` version.
* Removed the `push` trigger for all branches except `main`, leaving only `workflow_dispatch` and `pull_request` as triggers. (`[.github/workflows/test-framework-cli.yamlL7-L10](diffhunk://#diff-3b823426133c426c409ab0bec8905fb58185ad27ffa6c316b5e2fc9c7d86ef16L7-L10)`)
* Updated the `actions/checkout` step across multiple jobs to …

fix: fork checkout running the testing workflow

---

README.md

Looks like the quickstart was moved to another subsection of the docs

Fixing quickstart links in the README

---

packages/ts-moose-lib/src/dmv2/index.ts

This pull request includes a small change to the `View` class in the `packages/ts-moose-lib/src/dmv2/index.ts` file. The change modifies the SQL statement to create a regular view instead of a materialized view.

fix: view should create a view, not a materialized view

---

apps/framework-docs/src/components/product-badge.tsx

Trying to fix the color issue on Docs light mode

Fix aurora badge text color for light mode

---

.github/workflows/release-cli.yaml

This pull request introduces a new job in the GitHub Actions workflow to update the Moose CLI version index. The job is responsible for maintaining a JSON file that tracks versions of the Moose CLI, ensuring it is up-to-date and organized. Below are the key changes:
* **Job Definition**: A new job, `update-moose-version-index`, was added to the `.github/workflows/release-cli.yaml` file. It depends on the `build-and-publish-binaries` and `version` jobs and runs on `ubuntu-latest`.
* **Authentication Setup**: Configured authentication using the `google-github-actions/auth@v2` action with a specific service account and workload identity provider.
* **Cloud SDK Setup**: Installed the `gsutil` component using the `google-github-actions/setup-gcloud@v2` action to interact with Google Cloud …

chore: add index for moose versions in the download repo

---

rfd/0006/readme.mdx

This pull request introduces a new RFD (Request for Discussion) proposing a robust system for managing SQL dependencies in Moose, specifically targeting ClickHouse Materialized Views, Views, and Tables. The proposed solution addresses issues with unordered DDL execution during development by introducing explicit dependency tracking and a phased execution plan based on dependency analysis. Below is a breakdown of the most critical changes:
* **Explicit Dependency Tracking:** Introduced a `depends_on` property in the Moose SDK for defining dependencies between SQL resources (e.g., Tables, Views, Materialized Views). Dependencies are explicitly declared by users and transformed into structured JSON for processing in the Rust backend.
* **Rust Dependency Representation:** Extended the …

rfc(0006): improving change handling and sql dependencies

---

templates/python-empty/requirements.txt
templates/python-empty/setup.py

This pull request updates the Python project template by externalizing dependencies into a `requirements.txt` file and modifying the `setup.py` file to dynamically load dependencies from it. This change improves maintainability and aligns with best practices for Python packaging.
Dependency management improvements:
* [`templates/python-empty/requirements.txt`](diffhunk://#diff-43896c6f4ed7091d4c756f6ab12654a373c6c2d93f34e3ec1b226dcf76a36055R1-R5): Added a new `requirements.txt` file containing the project's dependencies (`kafka-python-ng==2.2.2`, `clickhouse-connect==0.7.16`, `requests==2.32.3`, `moose-cli`, `moose-lib`).
* [`templates/python-empty/setup.py`](diffhunk://#diff-a75898b918f909c7a48248b39966442faf930a16b407d108ec3aa4fd79408f03R3-R12): Updated `setup.py` to dynamically load …

fix: empty python template fix

---

apps/framework-cli/src/framework/python/wrappers/scripts/python_worker_wrapper/worker.py

This pull request modifies the behavior of the `start_worker` function in the `worker.py` script. The most important change is the replacement of an error-raising mechanism with a more graceful handling of cases where no scripts are found.
Error handling improvement:
* [`apps/framework-cli/src/framework/python/wrappers/scripts/python_worker_wrapper/worker.py`](diffhunk://#diff-5ad9516d1077ba2a15972b7f85444f806029433924d53caef1229e1869e6400bL126-R127): Changed the logging level from `error` to `info` and replaced the `raise ValueError` statement with a `return` to allow the function to exit gracefully when no scripts are found to register.

fix: no script should not raise an error

---

apps/framework-docs/src/pages/moose/reference/_meta.tsx
apps/framework-docs/src/pages/moose/reference/minimum-requirements.mdx

This pull request adds a new "Minimum Requirements" section to the Moose documentation, detailing both development and production setup requirements. It also updates the metadata file to include this new section.
* [`apps/framework-docs/src/pages/moose/reference/minimum-requirements.mdx`](diffhunk://#diff-26bc9434227283057300aedba79375b377c86776f9cbe2d2efdaad2df8c51e45R1-R25): Added a new "Minimum Requirements" page outlining system requirements for both development and production setups, including CPU, memory, disk, OS, and runtime specifications.
* [`apps/framework-docs/src/pages/moose/reference/_meta.tsx`](diffhunk://#diff-72567ac62ba1a7aa48392c60c70b4f096ff0fb45531b50adced601ed60e0c351R7): Added an entry for "Minimum Requirements" to the metadata object to include the new …

docs: add minimum requirements to the docs

---

rfd/0004/README.mdx

Is the mermaid diagram worth it? IDK

RFD-0004: Diagram with regular flow and migration flow.

---

apps/framework-cli/src/cli.rs
apps/framework-cli/src/cli/commands.rs
apps/framework-cli/src/cli/routines/peek.rs
apps/framework-docs/src/pages/moose/reference/moose-cli.mdx

This pull request refactors the `peek` command in the CLI to support peeking into both tables and streams, replacing the previous `data_model_name` and `topic` parameters with a unified `name` parameter and new flags for specifying resource types (`--table` and `--stream`). It also updates the documentation to reflect these changes.
* Updated the `Peek` command in `apps/framework-cli/src/cli/commands.rs` to replace `data_model_name` with `name` and added `--table` and `--stream` flags to specify the resource type. The default behavior is set to table if no flags are provided. (`[apps/framework-cli/src/cli/commands.rsL57-R74](diffhunk://#diff-e7f0aaaa20bae413611601b71b7dcb324e95b5d4bea41ab3c88fcb1efb4ba20fL57-R74)`)
* Modified the `top_command_handler` in `apps/framework-cli/src/cli.rs` to …

feat: update peek for dmv2

---

apps/framework-docs/src/pages/aurora/_meta.tsx
apps/framework-docs/src/pages/aurora/index.mdx
apps/framework-docs/src/pages/aurora/quickstart/_meta.tsx
apps/framework-docs/src/pages/aurora/quickstart/clickhouse-chat.mdx
apps/framework-docs/src/pages/aurora/quickstart/clickhouse-proj.mdx
apps/framework-docs/src/pages/aurora/quickstart/from-template.mdx
apps/framework-docs/src/pages/aurora/quickstart/index.mdx
apps/framework-docs/src/pages/aurora/reference/_meta.tsx
apps/framework-docs/src/pages/aurora/reference/cli-reference.mdx
apps/framework-docs/src/pages/aurora/reference/tool-reference.mdx

This pull request restructures the Aurora documentation by introducing reorganizing the Quickstart guides into individual pages, and updating navigation and content to improve clarity and usability. The changes include the addition of icons for better visual representation, the creation of dedicated pages for specific Quickstart guides, and the removal of the old consolidated Quickstart page.

docs: Structure and nesting in aurora docs

---

packages/ts-moose-lib/src/dmv2/index.ts
packages/ts-moose-lib/src/dmv2/internal.ts
packages/ts-moose-lib/src/dmv2/sdk/olapTable.ts

Realized I have way too many changes in my OlapTable PR so shipping it in small incremental bites.
This one starts the extraction of the OlapTable component in its own file

chore: move OlapTable to its own file

---

packages/ts-moose-lib/src/commons.ts
packages/ts-moose-lib/src/streaming-functions/runner.ts

when there's existing data in the kafka source topic
the streaming function runs
and tries to let moose know the progress metrics
when moose is not fully up
the http request failed and crashed the process

add on error handler to prevent crashing node process

---

packages/ts-connector-api/src/apiSource.test.ts
packages/ts-connector-api/src/apiSource.ts

Helps build the next url:
```
pagination: {
maxPages: 5,
delayBetweenRequests: 200,
getNextUrl: (context: APIContext<Cats[]>) => {
const page = parseInt(context.responseHeaders.get("pagination-page") ?? "0") + 1;
return `${context.requestUrl}&page=${page}`;
},
},
```

add req url to api context

---

apps/framework-docs/src/pages/aurora/reference/cli-reference.mdx

This pull request updates the CLI reference documentation for Aurora by removing sections related to features marked as "Coming Soon" and simplifying the description of experimental MCP tools.
Documentation updates:
* [`apps/framework-docs/src/pages/aurora/reference/cli-reference.mdx`](diffhunk://#diff-bf85b71967e6bcaf53db201164eedfd962aba58a67def492cb587b9de02ed517L165-L200): Removed the sections for `config models` and `login`, which were marked as "Coming Soon," along with their associated examples and argument tables. Simplified the description for `aurora config tools` by removing redundant information.

docs: minor changes to cli ref [PRO-185]

---

packages/ts-moose-lib/src/dmv2/sdk/consumptionApi.ts
packages/ts-moose-lib/src/dmv2/sdk/ingestApi.ts
packages/ts-moose-lib/src/dmv2/sdk/ingestPipeline.ts
packages/ts-moose-lib/src/dmv2/sdk/stream.ts
packages/ts-moose-lib/src/dmv2/typedBase.ts

I moved metadata to typed base and removed the references from the classes which extend it. 
The main value add here is the file location of where every object is instantiated.
NOTE/Caveat: Unfortunately the line #s are not accurate because of the compiler plugin.  I tried a variety of potentially low hanging fixes and none were successful. 
I am leaving the line #s in here because it may still be useful for approximation in large files, python will not have this restriction, and we may end up finding a fix and wont have to do anything special with the protobuf
https://linear.app/514/issue/AURORA-664/add-stacktrace-to-moose-metadata-objects

Add source Information to the TS serializer, move metadata to Typedbase

---

apps/framework-docs/src/pages/moose/building/workflows.mdx
packages/ts-moose-lib/src/dmv2/sdk/workflow.ts
pnpm-lock.yaml

This pull request includes updates to the Moose framework documentation and TypeScript library, along with cleanup in the `pnpm-lock.yaml` file. The most important changes include refining the `Task` class type parameters, updating examples in the documentation, and simplifying dependency definitions in the lock file.
* Modified the `Task` class in `packages/ts-moose-lib/src/dmv2/sdk/workflow.ts` to make the type parameters `T` and `R` required instead of optional. This ensures more explicit type definitions for tasks.
* Updated examples in `apps/framework-docs/src/pages/moose/building/workflows.mdx` to reflect the new `Task` class signature by adding `void` as the second type parameter where no return type is specified. [[1]](diffhunk://#diff-44b358d4e9fcbdb836a54a8e3ffcf4345e6da4cd94663a …

fix: docs worklows types are not optional

---

apps/framework-cli/src/cli/routines/scripts.rs
apps/framework-cli/src/infrastructure/orchestration/temporal_client.rs

The user will now see only the concise error message, e.g. Could not start workflow 'dog-fact-ingest': status: AlreadyExists, message: Workflow execution is already running. WorkflowId: dog-fact-ingest, RunId: ...

Enhance error handling in workflow execution error messages

---

apps/framework-cli/src/cli/logger.rs

From INFO to WARN. This change ensures that potential issues during log rotation are highlighted, preventing silent failures that could lead to disk space problems. Updated comments to clarify rationale for logging decisions.

Refactor log file cleanup to elevate error logging level

---

packages/ts-moose-lib/src/dmv2/internal.ts
packages/ts-moose-lib/src/moose-runner.ts

https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V22.md#requireesm-is-now-enabled-by-default

esm error hint

---

.github/workflows/codeql-analysis.yml
.github/workflows/format.yaml
.github/workflows/test-framework-cli.yaml

This pull request updates several GitHub Actions workflows to include a new trigger for `merge_group` events with the `checks_requested` type. This change ensures that workflows are triggered when checks are requested for merge groups.
Updates to GitHub Actions workflows:
* [`.github/workflows/codeql-analysis.yml`](diffhunk://#diff-63bd641104d10e25f141d518a16b22a151d125e12701df2f9e79734b23b90188R8-R9): Added a `merge_group` trigger with the `checks_requested` type under the `on` section.
* [`.github/workflows/format.yaml`](diffhunk://#diff-d671e201597b1543c1a04bea8290f7427b53646c708722719872792b39760b56R3-R4): Added a `merge_group` trigger with the `checks_requested` type under the `on` section.
* [`.github/workflows/test-framework-cli.yaml`](diffhunk://#diff-3b823426133c426c409ab0bec8905f …

chore: trigger on merge queue

---

apps/framework-cli/src/cli.rs
apps/framework-cli/src/cli/commands.rs
apps/framework-cli/src/cli/local_webserver.rs
apps/framework-cli/src/cli/routines/ls.rs
apps/framework-cli/src/cli/routines/scripts.rs
apps/framework-cli/src/framework/scripts.rs
apps/framework-docs/src/pages/moose/reference/moose-cli.mdx

Previously:
- `moose ls` was not showing registered workflows
- `moose workflow list` was only showing workflow history
Now:
- `moose ls` includes registered workflows
- `moose workflow list` does the same thing as `moose ls --type workflows`
- `moose workflow history` shows the history

cleanup workflow list cmd

---

apps/framework-cli/src/cli/local_webserver.rs
apps/framework-cli/src/cli/routines.rs
apps/framework-cli/src/framework/core/infrastructure_map.rs
apps/framework-cli/src/framework/core/plan.rs
apps/framework-cli/src/infrastructure/olap/clickhouse.rs
apps/framework-cli/src/infrastructure/olap/clickhouse/diff_strategy.rs
apps/framework-cli/src/infrastructure/olap/ddl_ordering.rs

This pull request introduces a ClickHouse-specific table diffing strategy to handle schema changes and updates the existing infrastructure to use this strategy. The changes include implementing the new strategy, integrating it into the infrastructure map diffing process, and refactoring the handling of table updates to rely on database-specific strategies. Below are the most important changes grouped by theme:
* Added a new module `diff_strategy` in `apps/framework-cli/src/infrastructure/olap/clickhouse/` that implements `ClickHouseTableDiffStrategy`. This strategy handles ClickHouse-specific limitations, such as requiring drop-and-create operations for changes to the `ORDER BY` clause, primary key structure, or deduplication settings.
* Updated `admin_plan_route` in …

fix: olap diff

---

apps/framework-cli/src/cli/routines/docker_packager.rs

**ENG-560: added ca-certs for moose docker builds**
required by kafka connections

ENG-560: ca-certs for moose

---

apps/framework-cli/src/cli/routines.rs
apps/framework-cli/src/cli/settings.rs
apps/framework-cli/src/cli/watcher.rs
apps/framework-cli/src/framework/core/execute.rs

This pull request introduces a new development setting that allows bypassing the execution of infrastructure changes (OLAP and streaming) in the CLI, enabling users to plan changes without actually applying them. To support this, the `Settings` and related structures are updated to be `Clone`, and the new setting is threaded through the relevant routines and execution logic.
**Development settings and configuration:**
* Added a new `bypass_infrastructure_execution` field to the `DevSettings` struct, allowing infrastructure execution to be skipped for OLAP and streaming changes via configuration or environment variable (`MOOSE_DEV__BYPASS_INFRASTRUCTURE_EXECUTION`).
* Implemented the `should_bypass_infrastructure_execution` method on the `Settings` struct to check this new setting.
* …

feat: add bypass for not executing changes

---

packages/ts-moose-lib/src/dataModels/dataModelTypes.ts
packages/ts-moose-lib/src/dmv2/sdk/olapTable.ts
packages/ts-moose-lib/src/sqlHelpers.ts

```
error TS2345: Argument of type 'IdentifierBrandedString' is not assignable to parameter of type 'Column | RawValue | OlapTable<any>'.
Type 'IdentifierBrandedString' is not assignable to type 'NonIdentifierBrandedString'.
Type 'IdentifierBrandedString' is not assignable to type '{ readonly __identifier_brand?: unique symbol | undefined; }'.
Types of property '__identifier_brand' are incompatible.
Type 'typeof __identifier_brand | undefined' is not assignable to type 'typeof __identifier_brand | undefined'. Two different types with this name exist, but they are unrelated.
Type 'typeof __identifier_brand' is not assignable to type 'typeof __identifier_brand'. Two different types with this name exist, but they are unrelated.
```

prevent putting identifiers in sql interpolator

---

templates/ads-b dlq/README.md
templates/ads-b-cf/README.md
templates/ads-b-frontend/README.md
templates/ads-b/README.md
templates/brainwaves/README.md
templates/github-dev-trends/Readme.md
templates/github-dev-trends/apps/moose-backend/README.md
templates/goodreads/README.md
templates/live-heartrate-leaderboard/README.md
templates/next-app-empty/README.md
templates/python-empty/README.md
templates/python/README.md
templates/typescript-empty/README.md
templates/typescript/README.md

This pull request updates the deployment instructions for several project templates to clarify the branding and provide more helpful documentation links. The main changes include updating the reference to the creators of Boreal from "Fiveonefour" to "514 Labs," and adding or improving sections about deploying Moose apps on Boreal, including links to the official deployment documentation.
**Branding and attribution updates:**
* Updated the deployment instructions in multiple `README.md` files to refer to "514 Labs" as the creators of Moose and Boreal instead of "Fiveonefour." [[1]](diffhunk://#diff-06041d676f234e08e5bec7fcb9b43aac018d7b7c6494d9aab5f3d650ef457b80L33-R33) [[2]](diffhunk://#diff-0c830d68ff4cdfb9c808eb0233cba2daee900d0cf99805c8a8f14e10c3e96985L232-R232) …

added deploy with boreal to template readmes (closes PM-352)

---

apps/framework-docs/src/components/export-requirement.tsx
apps/framework-docs/src/components/index.tsx
apps/framework-docs/src/pages/moose/apis.mdx
apps/framework-docs/src/pages/moose/apis/analytics-api.mdx
apps/framework-docs/src/pages/moose/apis/ingest-api.mdx
apps/framework-docs/src/pages/moose/getting-started/from-clickhouse.mdx
apps/framework-docs/src/pages/moose/getting-started/quickstart.mdx
apps/framework-docs/src/pages/moose/local-dev.mdx
apps/framework-docs/src/pages/moose/olap.mdx
apps/framework-docs/src/pages/moose/olap/model-materialized-view.mdx
apps/framework-docs/src/pages/moose/olap/model-table.mdx
apps/framework-docs/src/pages/moose/reference/ts-moose-lib.mdx
apps/framework-docs/src/pages/moose/streaming.mdx
apps/framework-docs/src/pages/moose/streaming/create-stream.mdx
apps/framework-docs/src/pages/moose/workflows.mdx

This pull request updates the Moose framework documentation to clarify and enforce best practices for exporting and importing data components, especially for TypeScript and Python projects. It introduces a new `ExportRequirement` component to highlight export/import requirements, updates code examples to use explicit exports, and improves cross-language guidance throughout the docs.
The most important changes are:
**Documentation improvements for export/import patterns:**
* Added a new `ExportRequirement` component (`export-requirement.tsx`) to visually call out export/import requirements for primitives like tables and APIs in the documentation. This component is now used in key docs pages to clarify the need for explicit exports in TypeScript and imports in Python. …

Document export pattern across docs (quickstart and primitives) (closes PM-382)

---

apps/framework-cli/src/cli/routines/docker_packager.rs

Trying to do this in a project: `"postinstall": "PLAYWRIGHT_BROWSERS_PATH=0 npx playwright install --with-deps chromium"`
But it fails because --with-deps need to install os-level deps and can't do that under the `moose` user.
It seems that the monorepo build already installs as root, so this changes the non-monorepo builds to do the same.

run install with deps

---

apps/create-moose-app/package.json
apps/framework-cli-e2e/package.json
apps/framework-docs/package.json
apps/moose-cli-npm/package.json
package.json
packages/design-system-base/package.json
packages/design-system-components/package.json
packages/eslint-config-custom/package.json
packages/event-capture/package.json
packages/tailwind-config/package.json
packages/ts-config/package.json
packages/ts-connector-api/package.json
packages/ts-connector-s3/package.json
packages/ts-moose-lib/package.json
packages/ts-moose-proto/package.json
scripts/ensure-safe-check.js
scripts/package.json

Add preinstall script to package.json's which ensures [@aikidosec/safe-chain](https://github.com/AikidoSec/safe-chain) is installed & configured when installing packages locally.
The preinstall script issues a warning and causes `pnpm install` to exit non-zero.
The check is only performed in non-CI environments.

ensure safe-chain during `pnpm install ...` on local dev

---

apps/framework-cli/src/cli.rs

This fixes the `moose seed ...` command output to include the required `--connection-string` flag.

add missing connection-string flag

---

apps/framework-cli-e2e/test/constants.ts
apps/framework-cli-e2e/test/templates.test.ts
apps/framework-cli-e2e/test/utils/database-utils.ts
apps/framework-cli-e2e/test/utils/index.ts
apps/framework-cli-e2e/test/utils/schema-definitions.ts
templates/python-tests/app/ingest/models.py
templates/typescript-tests/app/ingest/models.ts

This pull request introduces comprehensive schema validation for the framework CLI end-to-end (E2E) tests, ensuring that tables created by both TypeScript and Python templates match expected ClickHouse schemas. It adds detailed schema definitions, utilities for introspecting and validating ClickHouse tables, and expands the Python test models for robust type coverage. This helps catch schema mismatches early and improves confidence in template correctness.
The most important changes are:
**Schema Validation Infrastructure:**
* Added a new schema validation utility to `database-utils.ts`, including functions and types for introspecting ClickHouse tables, validating schemas, and printing results. This enables automated checks that created tables match expected structures, types, and …

chore: add tests for the different combination of schemas we support
